In [1]:
%matplotlib inline

# plotting
import matplotlib as mpl
mpl.style.use('ggplot')
import matplotlib.pyplot as plt
import tensorflow

# math and data manipulation
import numpy as np
import pandas as pd

# to handle paths
from pathlib import Path

# set random seeds 
from numpy.random import seed
#from tensorflow import set_random_seed

# Exploratory Analysis

## Data1: Training data

In [51]:
df = pd.read_csv("cold-start-consumption-forecasting-training-data.csv", sep=";", parse_dates=['timestamp'])
df['timestamp'] = pd.to_datetime(df['timestamp'], utc=True)
df.sort_values(by='timestamp', inplace=True)

### training on only one building (site_id=2)

In [52]:
df2 = df[df["site_id"]==2]

In [53]:
df2

,obs_id,site_id,timestamp,temperature,temperature_-1,temperature_-2,load,load_-1,load_-2,target
1221786,18469,2,2013-01-01 03:00:00+00:00,0.500000,1.000000,1.000000,52561.679251,51033.723459,49964.154405,53631.248306
29192,18470,2,2013-01-01 04:00:00+00:00,0.500000,0.500000,1.000000,55159.204098,52561.679251,51033.723459,62340.596321
56052,18471,2,2013-01-01 05:00:00+00:00,0.000000,0.500000,0.500000,58979.093579,55159.204098,52561.679251,106345.723136
1332108,18472,2,2013-01-01 06:00:00+00:00,0.000000,0.000000,0.500000,58520.706841,58979.093579,55159.204098,132473.767183
1063812,18473,2,2013-01-01 07:00:00+00:00,0.000000,0.000000,0.000000,59590.275895,58520.706841,58979.093579,160129.767021
...,...,...,...,...,...,...,...,...,...,...
438680,32888,2,2014-08-24 22:00:00+00:00,18.000000,18.500000,20.166667,65396.507906,66771.668119,65854.894643,173117.391255
438681,32889,2,2014-08-24 23:00:00+00:00,17.933333,18.000000,18.500000,66313.281381,65396.507906,66771.668119,177854.054211
359458,32890,2,2014-08-25 00:00:00+00:00,18.000000,17.933333,18.000000,72730.695708,66313.281381,65396.507906,172200.617780
1054107,32891,2,2014-08-25 01:00:00+00:00,17.000000,18.000000,17.933333,77314.563085,72730.695708,66313.281381,170978.253146
805671,32892,2,2014-08-25 02:00:00+00:00,16.633333,17.000000,18.000000,74869.833817,77314.563085,72730.695708,174492.551468

In [34]:
train2 = df2[:-24]
valid2 = df2[-24:]

In [35]:
valid2

,obs_id,site_id,timestamp,temperature,temperature_-1,temperature_-2,load,load_-1,load_-2,target
698361,32869,2,2014-08-24 03:00:00+00:00,15.000000,15.800000,16.000000,62646.187480,62798.983059,63410.165376,73036.286867
438678,32870,2,2014-08-24 04:00:00+00:00,15.000000,15.000000,15.800000,62035.005163,62646.187480,62798.983059,75481.016134
1054105,32871,2,2014-08-24 05:00:00+00:00,14.166667,15.000000,15.000000,62340.596321,62035.005163,62646.187480,167769.545982
448850,32872,2,2014-08-24 06:00:00+00:00,14.000000,14.166667,15.000000,60659.844950,62340.596321,62035.005163,189160.927073
698362,32873,2,2014-08-24 07:00:00+00:00,15.500000,14.000000,14.166667,58062.320103,60659.844950,62340.596321,244472.926750
1226299,32874,2,2014-08-24 08:00:00+00:00,16.633333,15.500000,14.000000,58215.115682,58062.320103,60659.844950,249820.772023
1226301,32875,2,2014-08-24 09:00:00+00:00,19.000000,16.633333,15.500000,58367.911262,58215.115682,58062.320103,255015.821716
913111,32876,2,2014-08-24 10:00:00+00:00,20.000000,19.000000,16.633333,58673.502420,58367.911262,58215.115682,259141.302355
805669,32877,2,2014-08-24 11:00:00+00:00,20.433333,20.000000,19.000000,60048.662633,58673.502420,58367.911262,245848.086963
359454,32878,2,2014-08-24 12:00:00+00:00,21.500000,20.433333,20.000000,59743.071475,60048.662633,58673.502420,249667.976444
1257014,32879,2,2014-08-24 13:00:00+00:00,22.500000,21.500000,20.433333,60048.662633,59743.071475,60048.662633,259599.689093
229439,32880,2,2014-08-24 14:00:00+00:00,22.966667,22.500000,21.500000,59284.684737,60048.662633,59743.071475,271670.539851
1054106,32881,2,2014-08-24 15:00:00+00:00,23.500000,22.966667,22.500000,60507.049371,59284.684737,60048.662633,272892.904485
913114,32882,2,2014-08-24 16:00:00+00:00,24.000000,23.500000,22.966667,60659.844950,60507.049371,59284.684737,244320.131171
438679,32883,2,2014-08-24 17:00:00+00:00,24.500000,24.000000,23.500000,59895.867054,60659.844950,60507.049371,246000.882543
229441,32884,2,2014-08-24 18:00:00+00:00,23.500000,24.500000,24.000000,60507.049371,59895.867054,60659.844950,249667.976444
359456,32885,2,2014-08-24 19:00:00+00:00,22.000000,23.500000,24.500000,60201.458212,60507.049371,59895.867054,198175.866247
229443,32886,2,2014-08-24 20:00:00+00:00,20.166667,22.000000,23.500000,65854.894643,60201.458212,60507.049371,218192.087125
913117,32887,2,2014-08-24 21:00:00+00:00,18.500000,20.166667,22.000000,66771.668119,65854.894643,60201.458212,202454.142465
438680,32888,2,2014-08-24 22:00:00+00:00,18.000000,18.500000,20.166667,65396.507906,66771.668119,65854.894643,173117.391255
438681,32889,2,2014-08-24 23:00:00+00:00,17.933333,18.000000,18.500000,66313.281381,65396.507906,66771.668119,177854.054211
359458,32890,2,2014-08-25 00:00:00+00:00,18.000000,17.933333,18.000000,72730.695708,66313.281381,65396.507906,172200.617780
1054107,32891,2,2014-08-25 01:00:00+00:00,17.000000,18.000000,17.933333,77314.563085,72730.695708,66313.281381,170978.253146
805671,32892,2,2014-08-25 02:00:00+00:00,16.633333,17.000000,18.000000,74869.833817,77314.563085,72730.695708,174492.551468

In [55]:
from autots import AutoTS
from sklearn.model_selection import train_test_split

In [56]:
# Define your model
model = AutoTS(
    forecast_length=24,  # adjust based on how far you want to forecast
    frequency='H',  # 'infer' will automatically detect the frequency
    ensemble='simple',  # use a simple ensemble of models
    model_list="fast_parallel",  # "superfast", "default", "fast_parallel"
    transformer_list="fast",  # "superfast",
    max_generations=1,  # number of iterations for model search
    num_validations=1,  # number of validations
    validation_method="backwards",  # type of validation
)

# Fit the model
model = model.fit(
    train2,
    date_col='timestamp',  # column with dates
    value_col='target',    # column with values to predict
    id_col='site_id',      # grouping (if applicable)
)

# Get the best model and predictions
prediction = model.predict()
print(prediction)

# Evaluate the model
forecast = prediction.forecast  # DataFrame of the forecast
print(forecast)
print("finished!")

Data frequency is: H, used frequency is: H
Model Number: 1 with model ARIMA in generation 0 of 1

 This problem is unconstrained.

RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =           17     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  1.09344D+01    |proj g|=  4.25758D-02

At iterate    1    f=  1.09306D+01    |proj g|=  2.86714D-02

At iterate    2    f=  1.09292D+01    |proj g|=  1.64552D-02

At iterate    3    f=  1.09277D+01    |proj g|=  1.19781D-02

At iterate    4    f=  1.09269D+01    |proj g|=  1.13415D-02

At iterate    5    f=  1.09267D+01    |proj g|=  1.03303D-02

At iterate    6    f=  1.09266D+01    |proj g|=  4.82664D-03

At iterate    7    f=  1.09265D+01    |proj g|=  5.76592D-03

At iterate    8    f=  1.09264D+01    |proj g|=  6.88976D-03

At iterate    9    f=  1.09262D+01    |proj g|=  7.80060D-03

At iterate   10    f=  1.09261D+01    |proj g|=  8.34055D-03

At iterate   11    f=  1.09260D+01    |proj g|=  5.16205D-03

At iterate   12    f=  1.09258D+01    |proj g|=  5.21981D-03

At iterate   13    f=  1.09257D+01    |proj g|=  8.51588D-03

At iterate   14    f=  1.09253D+01    |proj g|=  1.27684D-02

At iterate   15    f=  1.09251D+01    |proj g|=  1.37018D-02

At iterate   16    f=  1.09245D+01    |proj g|=  2.21310D-02

At iterate   17    f=  1.09235D+01    |proj g|=  2.17625D-02

At iterate   18    f=  1.09218D+01    |proj g|=  2.13899D-02

At iterate   19    f=  1.09209D+01    |proj g|=  1.66589D-02

At iterate   20    f=  1.09205D+01    |proj g|=  1.26144D-02

At iterate   21    f=  1.09202D+01    |proj g|=  1.28819D-02

At iterate   22    f=  1.09198D+01    |proj g|=  8.60077D-03

At iterate   23    f=  1.09194D+01    |proj g|=  1.24077D-02

At iterate   24    f=  1.09187D+01    |proj g|=  2.54862D-02

At iterate   25    f=  1.09180D+01    |proj g|=  3.33197D-02

At iterate   26    f=  1.09164D+01    |proj g|=  3.61188D-02

At iterate   27    f=  1.09155D+01    |proj g|=  2.66760D-02

At iterate   28    f=  1.09148D+01    |proj g|=  1.28424D-02

At iterate   29    f=  1.09147D+01    |proj g|=  7.40997D-03

At iterate   30    f=  1.09146D+01    |proj g|=  8.59909D-03

At iterate   31    f=  1.09144D+01    |proj g|=  5.67854D-03

At iterate   32    f=  1.09142D+01    |proj g|=  4.45138D-03

At iterate   33    f=  1.09141D+01    |proj g|=  5.31080D-03

At iterate   34    f=  1.09140D+01    |proj g|=  5.30024D-03

At iterate   35    f=  1.09139D+01    |proj g|=  3.58666D-03

At iterate   36    f=  1.09138D+01    |proj g|=  3.66668D-03

At iterate   37    f=  1.09137D+01    |proj g|=  5.55834D-03

At iterate   38    f=  1.09135D+01    |proj g|=  6.63223D-03

At iterate   39    f=  1.09129D+01    |proj g|=  1.68204D-02

At iterate   40    f=  1.09125D+01    |proj g|=  1.75317D-02

At iterate   41    f=  1.09119D+01    |proj g|=  1.12542D-02

At iterate   42    f=  1.09117D+01    |proj g|=  1.15856D-02

At iterate   43    f=  1.09116D+01    |proj g|=  1.43463D-02

At iterate   44    f=  1.09115D+01    |proj g|=  2.81086D-02

At iterate   45    f=  1.09113D+01    |proj g|=  1.10172D-02

At iterate   46    f=  1.09111D+01    |proj g|=  4.85931D-03

At iterate   47    f=  1.09108D+01    |proj g|=  1.63938D-02

At iterate   48    f=  1.09104D+01    |proj g|=  3.12448D-02

At iterate   49    f=  1.09092D+01    |proj g|=  3.05381D-02

At iterate   50    f=  1.09089D+01    |proj g|=  4.03838D-02

At iterate   51    f=  1.09080D+01    |proj g|=  2.10627D-02

At iterate   52    f=  1.09077D+01    |proj g|=  4.55526D-02

At iterate   53    f=  1.09072D+01    |proj g|=  3.79744D-02

At iterate   54    f=  1.09069D+01    |proj g|=  2.27175D-02

At iterate   55    f=  1.09065D+01    |proj g|=  2.85124D-02

At iterate   56    f=  1.09062D+01    |proj g|=  1.97396D-02

At iterate   57    f=  1.09054D+01    |proj g|=  2.65365D-02

At iterate   58    f=  1.09051D+01    |proj g|=  7.22950D-03

At iterate   59    f=  1.09050D+01    |proj g|=  2.24104D-02

At iterate   60    f=  1.09049D+01    |proj g|=  2.82735D-02

At iterate   61    f=  1.09048D+01    |proj g|=  1.49139D-02

At iterate   62    f=  1.09047D+01    |proj g|=  3.31436D-03

At iterate   63    f=  1.09046D+01    |proj g|=  4.61921D-03

At iterate   64    f=  1.09045D+01    |proj g|=  6.66345D-03

At iterate   65    f=  1.09044D+01    |proj g|=  2.52693D-02

At iterate   66    f=  1.09043D+01    |proj g|=  1.34076D-02

At iterate   67    f=  1.09042D+01    |proj g|=  4.00374D-02

At iterate   68    f=  1.09040D+01    |proj g|=  1.28891D-02

At iterate   69    f=  1.09038D+01    |proj g|=  1.10530D-02

At iterate   70    f=  1.09036D+01    |proj g|=  1.01354D-02

At iterate   71    f=  1.09034D+01    |proj g|=  3.37982D-02

At iterate   72    f=  1.09034D+01    |proj g|=  3.02904D-02

At iterate   73    f=  1.09034D+01    |proj g|=  3.10261D-03

At iterate   74    f=  1.09034D+01    |proj g|=  2.01927D-03

At iterate   75    f=  1.09034D+01    |proj g|=  1.46565D-03

At iterate   76    f=  1.09034D+01    |proj g|=  7.91624D-04

At iterate   77    f=  1.09034D+01    |proj g|=  2.14568D-03

At iterate   78    f=  1.09034D+01    |proj g|=  9.78196D-04

At iterate   79    f=  1.09034D+01    |proj g|=  7.57987D-04

At iterate   80    f=  1.09034D+01    |proj g|=  4.85839D-04

At iterate   81    f=  1.09034D+01    |proj g|=  2.76708D-04

At iterate   82    f=  1.09034D+01    |proj g|=  2.95803D-04

At iterate   83    f=  1.09034D+01    |proj g|=  4.67604D-03

At iterate   84    f=  1.09034D+01    |proj g|=  3.02457D-03

At iterate   85    f=  1.09034D+01    |proj g|=  9.85780D-04

At iterate   86    f=  1.09034D+01    |proj g|=  1.73018D-03

At iterate   87    f=  1.09034D+01    |proj g|=  2.39316D-03

At iterate   88    f=  1.09034D+01    |proj g|=  4.39840D-03

At iterate   89    f=  1.09034D+01    |proj g|=  8.60503D-03

At iterate   90    f=  1.09033D+01    |proj g|=  4.02648D-03

At iterate   91    f=  1.09033D+01    |proj g|=  4.49252D-03

At iterate   92    f=  1.09033D+01    |proj g|=  2.29703D-03

At iterate   93    f=  1.09032D+01    |proj g|=  4.03220D-03

At iterate   94    f=  1.09032D+01    |proj g|=  3.47152D-03

At iterate   95    f=  1.09032D+01    |proj g|=  2.05242D-03

At iterate   96    f=  1.09032D+01    |proj g|=  1.67681D-03

At iterate   97    f=  1.09032D+01    |proj g|=  4.37938D-03

At iterate   98    f=  1.09032D+01    |proj g|=  2.01214D-03

At iterate   99    f=  1.09032D+01    |proj g|=  5.70352D-04

At iterate  100    f=  1.09032D+01    |proj g|=  7.40187D-04

At iterate  101    f=  1.09032D+01    |proj g|=  1.14847D-03

At iterate  102    f=  1.09032D+01    |proj g|=  1.17064D-03

At iterate  103    f=  1.09032D+01    |proj g|=  1.35371D-03

At iterate  104    f=  1.09032D+01    |proj g|=  6.05997D-04

At iterate  105    f=  1.09032D+01    |proj g|=  3.85289D-03

At iterate  106    f=  1.09032D+01    |proj g|=  4.12128D-04

At iterate  107    f=  1.09032D+01    |proj g|=  2.01794D-04

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
   17    107    123      1     0     0   2.018D-04   1.090D+01
  F =   10.903233744699497

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
Model Number: 2 with model AverageValueNaive in generation 0 of 1
Model Number: 3 with model AverageValueNaive in generation 0 of 1
Model Number: 4 with model AverageValueNaive in generation 0 of 1
Model Number: 5 with model DatepartRegression in generation 0 of 1
Model Number: 6 with model DatepartRegression in generation 0 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/svm/_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

Model Number: 7 with model DatepartRegression in generation 0 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

Model Number: 8 with model DatepartRegression in generation 0 of 1
Epoch 1/50
450/450 [==============================] - 2s 1ms/step - loss: 0.3164
Epoch 2/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2811
Epoch 3/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2521
Epoch 4/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2000
Epoch 5/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1551
Epoch 6/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1413
Epoch 7/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1332
Epoch 8/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1276
Epoch 9/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1264
Epoch 10/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1238
Epoch 11/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1220
Epoch 12/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1197
Epoch 13/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1165
Epoch 14/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1155
Epoch 15/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1129
Epoch 16/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1133
Epoch 17/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1103
Epoch 18/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1100
Epoch 19/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1090
Epoch 20/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1051
Epoch 21/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1047
Epoch 22/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1048
Epoch 23/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1031
Epoch 24/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1018
Epoch 25/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0995
Epoch 26/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0989
Epoch 27/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0977
Epoch 28/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0954
Epoch 29/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0943
Epoch 30/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0929
Epoch 31/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0925
Epoch 32/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0904
Epoch 33/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0908
Epoch 34/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0886
Epoch 35/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0879
Epoch 36/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0868
Epoch 37/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0866
Epoch 38/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0842
Epoch 39/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0826
Epoch 40/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0826
Epoch 41/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0819
Epoch 42/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0803
Epoch 43/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0791
Epoch 44/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0778
Epoch 45/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0761
Epoch 46/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0759
Epoch 47/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0754
Epoch 48/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0748
Epoch 49/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0723
Epoch 50/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0725
1/1 [==============================] - 0s 293ms/step
Model Number: 9 with model ETS in generation 0 of 1
Model Number: 10 with model ETS in generation 0 of 1
Model Number: 11 with model GLM in generation 0 of 1
Model Number: 12 with model GLM in generation 0 of 1
Model Number: 13 with model GLS in generation 0 of 1
Model Number: 14 with model GLS in generation 0 of 1
Model Number: 15 with model LastValueNaive in generation 0 of 1
Model Number: 16 with model LastValueNaive in generation 0 of 1
Model Number: 17 with model LastValueNaive in generation 0 of 1
Model Number: 18 with model LastValueNaive in generation 0 of 1
Model Number: 19 with model SeasonalNaive in generation 0 of 1
Model Number: 20 with model SeasonalNaive in generation 0 of 1
Model Number: 21 with model SeasonalNaive in generation 0 of 1
Model Number: 22 with model UnobservedComponents in generation 0 of 1
Template Eval Error: TypeError('Cannot compare tz-naive and tz-aware datetime-like objects.') in model 22 in generation 0: UnobservedComponents
Model Number: 23 with model UnobservedComponents in generation 0 of 1
Model Number: 24 with model UnobservedComponents in generation 0 of 1
Model Number: 25 with model VAR in generation 0 of 1
Template Eval Error: ValueError('Only gave one variable to VAR') in model 25 in generation 0: VAR
Model Number: 26 with model VAR in generation 0 of 1
Template Eval Error: ValueError('Only gave one variable to VAR') in model 26 in generation 0: VAR
Model Number: 27 with model VECM in generation 0 of 1
Template Eval Error: ValueError('Only gave one variable to VECM') in model 27 in generation 0: VECM
Model Number: 28 with model VECM in generation 0 of 1
Template Eval Error: ValueError('Only gave one variable to VECM') in model 28 in generation 0: VECM
Model Number: 29 with model WindowRegression in generation 0 of 1
Model Number: 30 with model ConstantNaive in generation 0 of 1
Model Number: 31 with model FBProphet in generation 0 of 1
Template Eval Error: ModuleNotFoundError("No module named 'fbprophet'") in model 31 in generation 0: FBProphet
Model Number: 32 with model DatepartRegression in generation 0 of 1
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 32 in generation 0: DatepartRegression
Model Number: 33 with model SeasonalNaive in generation 0 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

Model Number: 34 with model DatepartRegression in generation 0 of 1
Model Number: 35 with model UnobservedComponents in generation 0 of 1
Template Eval Error: TypeError('Cannot compare tz-naive and tz-aware datetime-like objects.') in model 35 in generation 0: UnobservedComponents
Model Number: 36 with model UnobservedComponents in generation 0 of 1
Template Eval Error: TypeError('Cannot compare tz-naive and tz-aware datetime-like objects.') in model 36 in generation 0: UnobservedComponents
Model Number: 37 with model ETS in generation 0 of 1
Model Number: 38 with model VECM in generation 0 of 1
Template Eval Error: ValueError('Only gave one variable to VECM') in model 38 in generation 0: VECM
Model Number: 39 with model ARDL in generation 0 of 1
Template Eval Error: TypeError('Cannot compare tz-naive and tz-aware datetime-like objects.') in model 39 in generation 0: ARDL
Model Number: 40 with model MultivariateMotif in generation 0 of 1
Model Number: 41 with model MultivariateMotif in generation 0 of 1
Model Number: 42 with model UnivariateMotif in generation 0 of 1
Model Number: 43 with model UnivariateMotif in generation 0 of 1
Model Number: 44 with model SectionalMotif in generation 0 of 1
Model Number: 45 with model SectionalMotif in generation 0 of 1
Model Number: 46 with model FBProphet in generation 0 of 1
Template Eval Error: ModuleNotFoundError("No module named 'fbprophet'") in model 46 in generation 0: FBProphet
Model Number: 47 with model SeasonalNaive in generation 0 of 1
Model Number: 48 with model DatepartRegression in generation 0 of 1
Model Number: 49 with model NVAR in generation 0 of 1
Model Number: 50 with model Theta in generation 0 of 1
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            2     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  1.08570D+01    |proj g|=  3.77014D-06

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    2      0      1      0     0     0   3.770D-06   1.086D+01
  F =   10.856974795053290

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL

 This problem is unconstrained.

Model Number: 51 with model ARCH in generation 0 of 1
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 51 in generation 0: ARCH
Model Number: 52 with model Cassandra in generation 0 of 1
Model Number: 53 with model SeasonalityMotif in generation 0 of 1
Template Eval Error: TypeError('Cannot subtract tz-naive and tz-aware datetime-like objects') in model 53 in generation 0: SeasonalityMotif
Model Number: 54 with model ETS in generation 0 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/models/cassandra.py:1177: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  first_adjust.iloc[0] = 0.5
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/tools/percentile.py:47: RuntimeWarning: All-NaN slice encountered
  max_val = np.nanmax(arr)

Model Number: 55 with model FBProphet in generation 0 of 1
Template Eval Error: ModuleNotFoundError("No module named 'fbprophet'") in model 55 in generation 0: FBProphet
Model Number: 56 with model ARIMA in generation 0 of 1
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            5     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f= -1.05748D+01    |proj g|=  6.93147D+04

 This problem is unconstrained.

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    5      1     21      1     0     0   6.931D+04  -1.057D+01
  F =  -10.574823775684951

ABNORMAL_TERMINATION_IN_LNSRCH

 Line search cannot locate an adequate point after MAXLS
  function and gradient evaluations.
  Previous x, f and g restored.
 Possible causes: 1 error in function or gradient evaluation;
                  2 rounding error dominate computation.

Model Number: 57 with model GLM in generation 0 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning: overflow encountered in exp
  t = np.exp(-z)

Model Number: 58 with model UnobservedComponents in generation 0 of 1
Template Eval Error: TypeError('Cannot compare tz-naive and tz-aware datetime-like objects.') in model 58 in generation 0: UnobservedComponents
Model Number: 59 with model UnivariateMotif in generation 0 of 1
Model Number: 60 with model MultivariateMotif in generation 0 of 1
Model Number: 61 with model Theta in generation 0 of 1
Model Number: 62 with model ARDL in generation 0 of 1
Model Number: 63 with model ARCH in generation 0 of 1
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 63 in generation 0: ARCH
Model Number: 64 with model ConstantNaive in generation 0 of 1
Model Number: 65 with model LastValueNaive in generation 0 of 1
Model Number: 66 with model AverageValueNaive in generation 0 of 1
Model Number: 67 with model GLS in generation 0 of 1
Model Number: 68 with model SeasonalNaive in generation 0 of 1
Model Number: 69 with model VAR in generation 0 of 1
Template Eval Error: TypeError('Cannot compare tz-naive and tz-aware datetime-like objects.') in model 69 in generation 0: VAR
Model Number: 70 with model VECM in generation 0 of 1
Template Eval Error: TypeError('Cannot compare tz-naive and tz-aware datetime-like objects.') in model 70 in generation 0: VECM
Model Number: 71 with model WindowRegression in generation 0 of 1
Template Eval Error: Exception('Transformer AnomalyRemoval failed on fit') in model 71 in generation 0: WindowRegression
Model Number: 72 with model DatepartRegression in generation 0 of 1
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 72 in generation 0: DatepartRegression
Model Number: 73 with model SectionalMotif in generation 0 of 1
Model Number: 74 with model NVAR in generation 0 of 1
Model Number: 75 with model MAR in generation 0 of 1
Model Number: 76 with model RRVAR in generation 0 of 1
Template Eval Error: Exception('Transformer KalmanSmoothing failed on fit') in model 76 in generation 0: RRVAR
Model Number: 77 with model KalmanStateSpace in generation 0 of 1
Model Number: 78 with model MetricMotif in generation 0 of 1
Model Number: 79 with model Cassandra in generation 0 of 1
Template Eval Error: Exception('Transformer KalmanSmoothing failed on fit') in model 79 in generation 0: Cassandra
Model Number: 80 with model SeasonalityMotif in generation 0 of 1
Model Number: 81 with model FFT in generation 0 of 1
Model Number: 82 with model BallTreeMultivariateMotif in generation 0 of 1
Template Eval Error: TypeError('1D weights expected when shapes of a and weights differ.') in model 82 in generation 0: BallTreeMultivariateMotif
Model Number: 83 with model ConstantNaive in generation 0 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.343e+13, tolerance: 6.955e+09
  model = cd_fast.enet_coordinate_descent(

Model Number: 84 with model MetricMotif in generation 0 of 1
Model Number: 85 with model FFT in generation 0 of 1
Template Eval Error: Exception('Transformer LocalLinearTrend failed on inverse') in model 85 in generation 0: FFT
Model Number: 86 with model RRVAR in generation 0 of 1
Model Number: 87 with model FFT in generation 0 of 1
Model Number: 88 with model MAR in generation 0 of 1
Model Number: 89 with model SeasonalNaive in generation 0 of 1
Model Number: 90 with model SectionalMotif in generation 0 of 1
Model Number: 91 with model UnobservedComponents in generation 0 of 1
Model Number: 92 with model Theta in generation 0 of 1
Model Number: 93 with model SeasonalNaive in generation 0 of 1
Template Eval Error: Exception('Transformer RegressionFilter failed on fit') in model 93 in generation 0: SeasonalNaive
Model Number: 94 with model GLS in generation 0 of 1
Model Number: 95 with model GLM in generation 0 of 1
Template Eval Error: Exception('Transformer StandardScaler failed on fit') in model 95 in generation 0: GLM
Model Number: 96 with model FBProphet in generation 0 of 1
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 96 in generation 0: FBProphet
Model Number: 97 with model GLS in generation 0 of 1
Model Number: 98 with model LastValueNaive in generation 0 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=7.4395e-27): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

Model Number: 99 with model FBProphet in generation 0 of 1
Template Eval Error: Exception('Transformer KalmanSmoothing failed on fit') in model 99 in generation 0: FBProphet
Model Number: 100 with model UnobservedComponents in generation 0 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.448e+13, tolerance: 8.357e+09
  model = cd_fast.enet_coordinate_descent(

Model Number: 101 with model WindowRegression in generation 0 of 1
Model Number: 102 with model Theta in generation 0 of 1
Template Eval Error: Exception('Transformer AlignLastValue failed on inverse') in model 102 in generation 0: Theta
Model Number: 103 with model GLM in generation 0 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/statsmodels/genmod/families/family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "

Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 103 in generation 0: GLM
Model Number: 104 with model VECM in generation 0 of 1
Template Eval Error: ValueError('Only gave one variable to VECM') in model 104 in generation 0: VECM
Model Number: 105 with model FFT in generation 0 of 1
Template Eval Error: Exception('Transformer RegressionFilter failed on fit') in model 105 in generation 0: FFT
Model Number: 106 with model LastValueNaive in generation 0 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/statsmodels/genmod/families/links.py:527: RuntimeWarning: overflow encountered in exp
  return np.exp(z)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/statsmodels/genmod/families/family.py:1402: RuntimeWarning: divide by zero encountered in divide
  endog_mu = self._clean(endog / mu)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning: divide by zero encountered in log
  resid_dev -= endog_alpha * np.log(endog_alpha / mu_alpha)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning: invalid value encountered in multiply
  return 1. / (self.link.deriv(mu)**2 * self.variance(mu))
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/statsmodels/genmod/generalized_linear_model.py:1243: RuntimeWarning: invalid value encountered in multiply
  wlsendog = (lin_pred + self.family.link.deriv(mu) * (self.endog-mu)

Model Number: 107 with model VAR in generation 0 of 1
Template Eval Error: Exception('Transformer HolidayTransformer failed on fit') in model 107 in generation 0: VAR
Model Number: 108 with model LastValueNaive in generation 0 of 1
Template Eval Error: Exception('Transformer KalmanSmoothing failed on fit') in model 108 in generation 0: LastValueNaive
Model Number: 109 with model ARDL in generation 0 of 1
Model Number: 110 with model ETS in generation 0 of 1
Model Number: 111 with model FFT in generation 0 of 1
Template Eval Error: Exception('Transformer RegressionFilter failed on fit') in model 111 in generation 0: FFT
Model Number: 112 with model RRVAR in generation 0 of 1
Template Eval Error: Exception('Transformer AlignLastValue failed on inverse') in model 112 in generation 0: RRVAR
Model Number: 113 with model DatepartRegression in generation 0 of 1
Epoch 1/50
40/40 [==============================] - 2s 3ms/step - loss: 3265175296.0000
Epoch 2/50
40/40 [==============================] - 0s 3ms/step - loss: 3265090560.0000
Epoch 3/50
40/40 [==============================] - 0s 2ms/step - loss: 3264953344.0000
Epoch 4/50
40/40 [==============================] - 0s 3ms/step - loss: 3264617984.0000
Epoch 5/50
40/40 [==============================] - 0s 2ms/step - loss: 3264377856.0000
Epoch 6/50
40/40 [==============================] - 0s 2ms/step - loss: 3264164096.0000
Epoch 7/50
40/40 [==============================] - 0s 3ms/step - loss: 3263787520.0000
Epoch 8/50
40/40 [==============================] - 0s 2ms/step - loss: 3263500032.0000
Epoch 9/50
40/40 [==============================] - 0s 2ms/step - loss: 3263227904.0000
Epoch 10/50
40/40 [==============================] - 0s 2ms/step - loss: 3263014912.0000
Epoch 11/50
40/40 [==============================] - 0s 3ms/step - loss: 3262819584.0000
Epoch 12/50
40/40 [==============================] - 0s 2ms/step - loss: 3262628352.0000
Epoch 13/50
40/40 [==============================] - 0s 2ms/step - loss: 3262449408.0000
Epoch 14/50
40/40 [==============================] - 0s 2ms/step - loss: 3262279936.0000
Epoch 15/50
40/40 [==============================] - 0s 2ms/step - loss: 3262149376.0000
Epoch 16/50
40/40 [==============================] - 0s 2ms/step - loss: 3261961984.0000
Epoch 17/50
40/40 [==============================] - 0s 2ms/step - loss: 3261816576.0000
Epoch 18/50
40/40 [==============================] - 0s 2ms/step - loss: 3261667072.0000
Epoch 19/50
40/40 [==============================] - 0s 2ms/step - loss: 3261920768.0000
Epoch 20/50
40/40 [==============================] - 0s 2ms/step - loss: 3261359872.0000
Epoch 21/50
40/40 [==============================] - 0s 2ms/step - loss: 3261251584.0000
Epoch 22/50
40/40 [==============================] - 0s 2ms/step - loss: 3261056000.0000
Epoch 23/50
40/40 [==============================] - 0s 2ms/step - loss: 3260887296.0000
Epoch 24/50
40/40 [==============================] - 0s 2ms/step - loss: 3260721152.0000
Epoch 25/50
40/40 [==============================] - 0s 2ms/step - loss: 3260566272.0000
Epoch 26/50
40/40 [==============================] - 0s 2ms/step - loss: 3260422400.0000
Epoch 27/50
40/40 [==============================] - 0s 2ms/step - loss: 3260277248.0000
Epoch 28/50
40/40 [==============================] - 0s 2ms/step - loss: 3260116224.0000
Epoch 29/50
40/40 [==============================] - 0s 2ms/step - loss: 3259971840.0000
Epoch 30/50
40/40 [==============================] - 0s 2ms/step - loss: 3259822080.0000
Epoch 31/50
40/40 [==============================] - 0s 2ms/step - loss: 3259668224.0000
Epoch 32/50
40/40 [==============================] - 0s 2ms/step - loss: 3259526656.0000
Epoch 33/50
40/40 [==============================] - 0s 2ms/step - loss: 3259368448.0000
Epoch 34/50
40/40 [==============================] - 0s 2ms/step - loss: 3259153664.0000
Epoch 35/50
40/40 [==============================] - 0s 2ms/step - loss: 3259040512.0000
Epoch 36/50
40/40 [==============================] - 0s 2ms/step - loss: 3258794752.0000
Epoch 37/50
40/40 [==============================] - 0s 2ms/step - loss: 3258739968.0000
Epoch 38/50
40/40 [==============================] - 0s 2ms/step - loss: 3258606592.0000
Epoch 39/50
40/40 [==============================] - 0s 2ms/step - loss: 3258342912.0000
Epoch 40/50
40/40 [==============================] - 0s 2ms/step - loss: 3258183424.0000
Epoch 41/50
40/40 [==============================] - 0s 2ms/step - loss: 3258012416.0000
Epoch 42/50
40/40 [==============================] - 0s 2ms/step - loss: 3257854976.0000
Epoch 43/50
40/40 [==============================] - 0s 2ms/step - loss: 3257730560.0000
Epoch 44/50
40/40 [==============================] - 0s 2ms/step - loss: 3257608704.0000
Epoch 45/50
40/40 [==============================] - 0s 2ms/step - loss: 3257417472.0000
Epoch 46/50
40/40 [==============================] - 0s 2ms/step - loss: 3257257728.0000
Epoch 47/50
40/40 [==============================] - 0s 2ms/step - loss: 3257122560.0000
Epoch 48/50
40/40 [==============================] - 0s 2ms/step - loss: 3256980736.0000
Epoch 49/50
40/40 [==============================] - 0s 2ms/step - loss: 3256827136.0000
Epoch 50/50
40/40 [==============================] - 0s 2ms/step - loss: 3256666624.0000
1/1 [==============================] - 0s 283ms/step
Template Eval Error: Exception('Transformer CenterSplit failed on inverse') in model 113 in generation 0: DatepartRegression
Model Number: 114 with model Theta in generation 0 of 1
Model Number: 115 with model LastValueNaive in generation 0 of 1
Model Number: 116 with model FBProphet in generation 0 of 1
Template Eval Error: ModuleNotFoundError("No module named 'fbprophet'") in model 116 in generation 0: FBProphet
Model Number: 117 with model LastValueNaive in generation 0 of 1
Model Number: 118 with model KalmanStateSpace in generation 0 of 1
Model Number: 119 with model Theta in generation 0 of 1
Model Number: 120 with model SeasonalityMotif in generation 0 of 1
Model Number: 121 with model GLM in generation 0 of 1
Template Eval Error: ValueError('The first guess on the deviance function returned a nan.  This could be a boundary  problem and should be reported.') in model 121 in generation 0: GLM
Model Number: 122 with model SeasonalNaive in generation 0 of 1
Model Number: 123 with model AverageValueNaive in generation 0 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/statsmodels/genmod/families/family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning: divide by zero encountered in log
  resid_dev -= endog_alpha * np.log(endog_alpha / mu_alpha)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning: invalid value encountered in multiply
  resid_dev -= endog_alpha * np.log(endog_alpha / mu_alpha)

Model Number: 124 with model LastValueNaive in generation 0 of 1
Template Eval Error: Exception('Transformer LocalLinearTrend failed on inverse') in model 124 in generation 0: LastValueNaive
Model Number: 125 with model SeasonalityMotif in generation 0 of 1
Model Number: 126 with model WindowRegression in generation 0 of 1
Model Number: 127 with model VECM in generation 0 of 1
Template Eval Error: Exception('Transformer KalmanSmoothing failed on fit') in model 127 in generation 0: VECM
Model Number: 128 with model SeasonalNaive in generation 0 of 1
Model Number: 129 with model SeasonalNaive in generation 0 of 1
Model Number: 130 with model ETS in generation 0 of 1
Model Number: 131 with model ETS in generation 0 of 1
Model Number: 132 with model ETS in generation 0 of 1
Model Number: 133 with model SectionalMotif in generation 0 of 1
Template Eval Error: Exception('Transformer AlignLastValue failed on inverse') in model 133 in generation 0: SectionalMotif
Model Number: 134 with model MetricMotif in generation 0 of 1
Template Eval Error: Exception('Transformer AlignLastValue failed on inverse') in model 134 in generation 0: MetricMotif
Model Number: 135 with model GLM in generation 0 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/statsmodels/genmod/families/family.py:445: RuntimeWarning: divide by zero encountered in divide
  endog_mu = self._clean(endog / mu)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning: divide by zero encountered in divide
  return 1. / (self.link.deriv(mu)**2 * self.variance(mu))
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/statsmodels/genmod/families/family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning: invalid value encountered in log
  resid_dev -= endog_alpha * np.log(endog_alpha / mu_alpha)

Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 135 in generation 0: GLM
Model Number: 136 with model GLM in generation 0 of 1
Template Eval Error: ValueError('The first guess on the deviance function returned a nan.  This could be a boundary  problem and should be reported.') in model 136 in generation 0: GLM
Model Number: 137 with model KalmanStateSpace in generation 0 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/tools/fast_kalman.py:1301: RuntimeWarning: overflow encountered in matmul
  return np.matmul(A, B)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/tools/fast_kalman.py:1301: RuntimeWarning: invalid value encountered in matmul
  return np.matmul(A, B)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/tools/fast_kalman.py:1314: RuntimeWarning: invalid value encountered in matmul
  return np.matmul(A, np.swapaxes(B, -1, -2))

Model Number: 138 with model RRVAR in generation 0 of 1
Model Number: 139 with model UnobservedComponents in generation 0 of 1
Model Number: 140 with model ARIMA in generation 0 of 1
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            2     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  1.19926D+01    |proj g|=  4.12889D-05

At iterate    1    f=  1.19926D+01    |proj g|=  3.07550D-05

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    2      1      3      1     0     0   3.075D-05   1.199D+01
  F =   11.992553728783971

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH

 This problem is unconstrained.

RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            2     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f= -4.71584D-01    |proj g|=  6.05216D-04

At iterate    1    f= -4.71584D-01    |proj g|=  2.98401D-04

 This problem is unconstrained.

At iterate    2    f= -4.71584D-01    |proj g|=  2.98401D-04

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    2      2     34      2     0     0   2.984D-04  -4.716D-01
  F = -0.47158418189654766

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
Template Eval Error: Exception('Transformer CenterSplit failed on inverse') in model 140 in generation 0: ARIMA
Model Number: 141 with model BallTreeMultivariateMotif in generation 0 of 1
Model Number: 142 with model LastValueNaive in generation 0 of 1
Template Eval Error: Exception('Transformer AlignLastValue failed on inverse') in model 142 in generation 0: LastValueNaive
Model Number: 143 with model LastValueNaive in generation 0 of 1

 Bad direction in the line search;
   refresh the lbfgs memory and restart the iteration.

Model Number: 144 with model GLS in generation 0 of 1
Model Number: 145 with model BallTreeMultivariateMotif in generation 0 of 1
Model Number: 146 with model ConstantNaive in generation 0 of 1
Model Number: 147 with model ETS in generation 0 of 1
Model Number: 148 with model FBProphet in generation 0 of 1
Template Eval Error: Exception('Transformer RegressionFilter failed on fit') in model 148 in generation 0: FBProphet
Model Number: 149 with model RRVAR in generation 0 of 1
Model Number: 150 with model SeasonalNaive in generation 0 of 1
Model Number: 151 with model SeasonalNaive in generation 0 of 1
Model Number: 152 with model AverageValueNaive in generation 0 of 1
Model Number: 153 with model VAR in generation 0 of 1
Template Eval Error: ValueError('Only gave one variable to VAR') in model 153 in generation 0: VAR
Model Number: 154 with model RRVAR in generation 0 of 1
Model Number: 155 with model RRVAR in generation 0 of 1
Model Number: 156 with model SeasonalityMotif in generation 0 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/tools/transform.py:2411: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  return (df - self.means.shift(self.lag).values[..., None]).fillna(

Template Eval Error: TypeError('Cannot subtract tz-naive and tz-aware datetime-like objects') in model 156 in generation 0: SeasonalityMotif
Model Number: 157 with model GLS in generation 0 of 1
Template Eval Error: Exception('Transformer LocalLinearTrend failed on inverse') in model 157 in generation 0: GLS
Model Number: 158 with model RRVAR in generation 0 of 1
Template Eval Error: Exception('Transformer Detrend failed on fit') in model 158 in generation 0: RRVAR
Model Number: 159 with model WindowRegression in generation 0 of 1
Model Number: 160 with model GLS in generation 0 of 1
Model Number: 161 with model ConstantNaive in generation 0 of 1
Model Number: 162 with model KalmanStateSpace in generation 0 of 1
Model Number: 163 with model MultivariateMotif in generation 0 of 1
Model Number: 164 with model LastValueNaive in generation 0 of 1
Model Number: 165 with model Cassandra in generation 0 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/models/cassandra.py:1177: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  first_adjust.iloc[0] = 0.5

Model Number: 166 with model SeasonalNaive in generation 0 of 1
Model Number: 167 with model MAR in generation 0 of 1
Template Eval Error: ValueError('Shape of passed values is (7, 1), indices imply (24, 1)') in model 167 in generation 0: MAR
Model Number: 168 with model MetricMotif in generation 0 of 1
Model Number: 169 with model VAR in generation 0 of 1
Template Eval Error: ValueError('Only gave one variable to VAR') in model 169 in generation 0: VAR
Model Number: 170 with model MultivariateMotif in generation 0 of 1
Template Eval Error: Exception('Transformer Detrend failed on fit') in model 170 in generation 0: MultivariateMotif
Model Number: 171 with model KalmanStateSpace in generation 0 of 1
Template Eval Error: Exception('Transformer RegressionFilter failed on fit') in model 171 in generation 0: KalmanStateSpace
Model Number: 172 with model AverageValueNaive in generation 0 of 1
Template Eval Error: Exception('Transformer RegressionFilter failed on fit') in model 172 in generation 0: AverageValueNaive
Model Number: 173 with model LastValueNaive in generation 0 of 1
Model Number: 174 with model ETS in generation 0 of 1
Model Number: 175 with model Theta in generation 0 of 1
Model Number: 176 with model ARCH in generation 0 of 1
Template Eval Error: Exception('Transformer KalmanSmoothing failed on fit') in model 176 in generation 0: ARCH
Model Number: 177 with model VAR in generation 0 of 1
Template Eval Error: ValueError('Only gave one variable to VAR') in model 177 in generation 0: VAR
Model Number: 178 with model MAR in generation 0 of 1
Model Number: 179 with model BallTreeMultivariateMotif in generation 0 of 1
Template Eval Error: Exception('Transformer KalmanSmoothing failed on fit') in model 179 in generation 0: BallTreeMultivariateMotif
Model Number: 180 with model KalmanStateSpace in generation 0 of 1
Model Number: 181 with model MAR in generation 0 of 1
Model Number: 182 with model BallTreeMultivariateMotif in generation 0 of 1
Model Number: 183 with model LastValueNaive in generation 0 of 1
Template Eval Error: Exception('Transformer AlignLastValue failed on inverse') in model 183 in generation 0: LastValueNaive
Model Number: 184 with model BallTreeMultivariateMotif in generation 0 of 1
Model Number: 185 with model MetricMotif in generation 0 of 1
Template Eval Error: Exception('Transformer RegressionFilter failed on fit') in model 185 in generation 0: MetricMotif
Model Number: 186 with model MultivariateMotif in generation 0 of 1
Model Number: 187 with model GLM in generation 0 of 1
Template Eval Error: Exception('Transformer KalmanSmoothing failed on fit') in model 187 in generation 0: GLM
Model Number: 188 with model UnivariateMotif in generation 0 of 1
Template Eval Error: Exception('Transformer AlignLastValue failed on inverse') in model 188 in generation 0: UnivariateMotif
Model Number: 189 with model FFT in generation 0 of 1
Model Number: 190 with model VAR in generation 0 of 1
Template Eval Error: ValueError('Only gave one variable to VAR') in model 190 in generation 0: VAR
Model Number: 191 with model KalmanStateSpace in generation 0 of 1
Model Number: 192 with model ConstantNaive in generation 0 of 1
Model Number: 193 with model GLS in generation 0 of 1
Model Number: 194 with model GLS in generation 0 of 1
Model Number: 195 with model SeasonalityMotif in generation 0 of 1
Model Number: 196 with model GLM in generation 0 of 1
Model Number: 197 with model DatepartRegression in generation 0 of 1
Model Number: 198 with model LastValueNaive in generation 0 of 1
New Generation: 1 of 1
Model Number: 199 with model ConstantNaive in generation 1 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.343e+13, tolerance: 6.955e+09
  model = cd_fast.enet_coordinate_descent(

Model Number: 200 with model FFT in generation 1 of 1
Model Number: 201 with model GLS in generation 1 of 1
Template Eval Error: Exception('Transformer Detrend failed on fit') in model 201 in generation 1: GLS
Model Number: 202 with model DatepartRegression in generation 1 of 1
Epoch 1/50
450/450 [==============================] - 2s 1ms/step - loss: 37395.8867
Epoch 2/50
450/450 [==============================] - 0s 1ms/step - loss: 37380.2461
Epoch 3/50
450/450 [==============================] - 0s 1ms/step - loss: 37368.8477
Epoch 4/50
450/450 [==============================] - 0s 1ms/step - loss: 37358.3828
Epoch 5/50
450/450 [==============================] - 0s 1ms/step - loss: 37348.1992
Epoch 6/50
450/450 [==============================] - 0s 1ms/step - loss: 37338.3633
Epoch 7/50
450/450 [==============================] - 0s 1ms/step - loss: 37328.4844
Epoch 8/50
450/450 [==============================] - 0s 1ms/step - loss: 37318.9609
Epoch 9/50
450/450 [==============================] - 0s 1ms/step - loss: 37309.3203
Epoch 10/50
450/450 [==============================] - 0s 1ms/step - loss: 37299.1523
Epoch 11/50
450/450 [==============================] - 0s 1ms/step - loss: 37289.6367
Epoch 12/50
450/450 [==============================] - 0s 1ms/step - loss: 37280.1172
Epoch 13/50
450/450 [==============================] - 0s 1ms/step - loss: 37270.2383
Epoch 14/50
450/450 [==============================] - 0s 1ms/step - loss: 37260.8359
Epoch 15/50
450/450 [==============================] - 0s 1ms/step - loss: 37251.6289
Epoch 16/50
450/450 [==============================] - 1s 1ms/step - loss: 37241.4844
Epoch 17/50
450/450 [==============================] - 0s 1ms/step - loss: 37232.9023
Epoch 18/50
450/450 [==============================] - 0s 1ms/step - loss: 37222.3594
Epoch 19/50
450/450 [==============================] - 0s 1ms/step - loss: 37212.6523
Epoch 20/50
450/450 [==============================] - 0s 1ms/step - loss: 37203.8359
Epoch 21/50
450/450 [==============================] - 0s 1ms/step - loss: 37193.9492
Epoch 22/50
450/450 [==============================] - 0s 1ms/step - loss: 37183.9727
Epoch 23/50
450/450 [==============================] - 0s 1ms/step - loss: 37174.4180
Epoch 24/50
450/450 [==============================] - 0s 1ms/step - loss: 37164.6758
Epoch 25/50
450/450 [==============================] - 1s 1ms/step - loss: 37155.1133
Epoch 26/50
450/450 [==============================] - 0s 1ms/step - loss: 37147.8477
Epoch 27/50
450/450 [==============================] - 0s 1ms/step - loss: 37137.1523
Epoch 28/50
450/450 [==============================] - 0s 1ms/step - loss: 37126.1445
Epoch 29/50
450/450 [==============================] - 0s 1ms/step - loss: 37116.7305
Epoch 30/50
450/450 [==============================] - 0s 1ms/step - loss: 37106.9570
Epoch 31/50
450/450 [==============================] - 0s 1000us/step - loss: 37102.3086
Epoch 32/50
450/450 [==============================] - 0s 1ms/step - loss: 37088.1250
Epoch 33/50
450/450 [==============================] - 0s 1ms/step - loss: 37079.3867
Epoch 34/50
450/450 [==============================] - 0s 1ms/step - loss: 37071.3906
Epoch 35/50
450/450 [==============================] - 0s 1ms/step - loss: 37060.7852
Epoch 36/50
450/450 [==============================] - 0s 998us/step - loss: 37048.4961
Epoch 37/50
450/450 [==============================] - 0s 997us/step - loss: 37040.1562
Epoch 38/50
450/450 [==============================] - 0s 1ms/step - loss: 37039.1602
Epoch 39/50
450/450 [==============================] - 0s 1ms/step - loss: 37019.9883
Epoch 40/50
450/450 [==============================] - 0s 1ms/step - loss: 37010.7031
Epoch 41/50
450/450 [==============================] - 0s 1ms/step - loss: 37009.9961
Epoch 42/50
450/450 [==============================] - 0s 1ms/step - loss: 36992.4414
Epoch 43/50
450/450 [==============================] - 0s 1ms/step - loss: 36983.3203
Epoch 44/50
450/450 [==============================] - 0s 1ms/step - loss: 36973.8555
Epoch 45/50
450/450 [==============================] - 0s 1ms/step - loss: 36963.7891
Epoch 46/50
450/450 [==============================] - 0s 1ms/step - loss: 36955.4375
Epoch 47/50
450/450 [==============================] - 0s 1ms/step - loss: 36944.6719
Epoch 48/50
450/450 [==============================] - 0s 1ms/step - loss: 36935.2266
Epoch 49/50
450/450 [==============================] - 0s 1ms/step - loss: 36927.6289
Epoch 50/50
450/450 [==============================] - 0s 1ms/step - loss: 36914.1836
1/1 [==============================] - 0s 284ms/step
Model Number: 203 with model ETS in generation 1 of 1
Model Number: 204 with model GLM in generation 1 of 1
Model Number: 205 with model ETS in generation 1 of 1
Model Number: 206 with model ETS in generation 1 of 1
Model Number: 207 with model MultivariateMotif in generation 1 of 1
Template Eval Error: Exception('Transformer AlignLastValue failed on inverse') in model 207 in generation 1: MultivariateMotif
Model Number: 208 with model Theta in generation 1 of 1
Model Number: 209 with model ETS in generation 1 of 1
Model Number: 210 with model BallTreeMultivariateMotif in generation 1 of 1
Template Eval Error: TypeError('1D weights expected when shapes of a and weights differ.') in model 210 in generation 1: BallTreeMultivariateMotif
Model Number: 211 with model SeasonalityMotif in generation 1 of 1
Model Number: 212 with model RRVAR in generation 1 of 1
Model Number: 213 with model SectionalMotif in generation 1 of 1
Model Number: 214 with model LastValueNaive in generation 1 of 1
Model Number: 215 with model KalmanStateSpace in generation 1 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/tools/fast_kalman.py:1314: RuntimeWarning: overflow encountered in matmul
  return np.matmul(A, np.swapaxes(B, -1, -2))
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/tools/fast_kalman.py:1301: RuntimeWarning: overflow encountered in matmul
  return np.matmul(A, B)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/tools/fast_kalman.py:1301: RuntimeWarning: invalid value encountered in matmul
  return np.matmul(A, B)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/tools/fast_kalman.py:1319: RuntimeWarning: overflow encountered in multiply
  return a * b.transpose((0, 2, 1))
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/tools/fast_kalman.py:1314: RuntimeWarning: invalid value encountered in matmul
  return np.matmul(A, np.swapaxes(B, -1, -2))
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/models/basics.py:2157: RuntimeWarning: Mean of empty slice
  result_score = np.nansum(np.nanmean(upper_pl + lower_pl, axis=0) / scaler)

Template Eval Error: Exception('Transformer AlignLastValue failed on inverse') in model 215 in generation 1: KalmanStateSpace
Model Number: 216 with model SeasonalNaive in generation 1 of 1
Model Number: 217 with model DatepartRegression in generation 1 of 1
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 217 in generation 1: DatepartRegression
Model Number: 218 with model LastValueNaive in generation 1 of 1
Model Number: 219 with model SeasonalityMotif in generation 1 of 1
Template Eval Error: TypeError('Cannot subtract tz-naive and tz-aware datetime-like objects') in model 219 in generation 1: SeasonalityMotif
Model Number: 220 with model ETS in generation 1 of 1
Template Eval Error: Exception('Transformer RegressionFilter failed on fit') in model 220 in generation 1: ETS
Model Number: 221 with model SeasonalNaive in generation 1 of 1
Model Number: 222 with model ETS in generation 1 of 1
Model Number: 223 with model BallTreeMultivariateMotif in generation 1 of 1
Model Number: 224 with model MetricMotif in generation 1 of 1
Model Number: 225 with model Theta in generation 1 of 1
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            2     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  1.08567D+01    |proj g|=  3.86038D-06

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    2      0      1      0     0     0   3.860D-06   1.086D+01
  F =   10.856728730467989

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL

 This problem is unconstrained.

Model Number: 226 with model UnobservedComponents in generation 1 of 1
Template Eval Error: ValueError("regression_type='User' but no future_regressor supplied") in model 226 in generation 1: UnobservedComponents
Model Number: 227 with model ARDL in generation 1 of 1
Model Number: 228 with model ETS in generation 1 of 1
Model Number: 229 with model KalmanStateSpace in generation 1 of 1
Model Number: 230 with model ARDL in generation 1 of 1
Template Eval Error: TypeError('Cannot compare tz-naive and tz-aware datetime-like objects.') in model 230 in generation 1: ARDL
Model Number: 231 with model ETS in generation 1 of 1
Model Number: 232 with model BallTreeMultivariateMotif in generation 1 of 1
Template Eval Error: TypeError('1D weights expected when shapes of a and weights differ.') in model 232 in generation 1: BallTreeMultivariateMotif
Model Number: 233 with model WindowRegression in generation 1 of 1
Model Number: 234 with model ConstantNaive in generation 1 of 1
Model Number: 235 with model GLS in generation 1 of 1
Model Number: 236 with model AverageValueNaive in generation 1 of 1
Model Number: 237 with model UnivariateMotif in generation 1 of 1
Model Number: 238 with model GLS in generation 1 of 1
Model Number: 239 with model MAR in generation 1 of 1
Template Eval Error: ValueError('Shape of passed values is (7, 1), indices imply (24, 1)') in model 239 in generation 1: MAR
Model Number: 240 with model SeasonalNaive in generation 1 of 1
Model Number: 241 with model SeasonalNaive in generation 1 of 1
Template Eval Error: Exception('Transformer LocalLinearTrend failed on inverse') in model 241 in generation 1: SeasonalNaive
Model Number: 242 with model MetricMotif in generation 1 of 1
Model Number: 243 with model AverageValueNaive in generation 1 of 1
Model Number: 244 with model WindowRegression in generation 1 of 1
Template Eval Error: ModuleNotFoundError("No module named 'lightgbm'") in model 244 in generation 1: WindowRegression
Model Number: 245 with model SectionalMotif in generation 1 of 1
Model Number: 246 with model Cassandra in generation 1 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/models/cassandra.py:1177: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  first_adjust.iloc[0] = 0.5

Template Eval Error: Exception('Transformer AlignLastValue failed on inverse') in model 246 in generation 1: Cassandra
Model Number: 247 with model UnobservedComponents in generation 1 of 1
Template Eval Error: TypeError('Cannot compare tz-naive and tz-aware datetime-like objects.') in model 247 in generation 1: UnobservedComponents
Model Number: 248 with model Theta in generation 1 of 1
Model Number: 249 with model UnobservedComponents in generation 1 of 1
Model Number: 250 with model MultivariateMotif in generation 1 of 1
Template Eval Error: Exception('Transformer AlignLastValue failed on inverse') in model 250 in generation 1: MultivariateMotif
Model Number: 251 with model DatepartRegression in generation 1 of 1
Epoch 1/200
450/450 [==============================] - 3s 3ms/step - loss: 1.3157
Epoch 2/200
450/450 [==============================] - 1s 3ms/step - loss: 0.2884
Epoch 3/200
450/450 [==============================] - 1s 3ms/step - loss: 0.2152
Epoch 4/200
450/450 [==============================] - 1s 3ms/step - loss: 0.1833
Epoch 5/200
450/450 [==============================] - 1s 3ms/step - loss: 0.1627
Epoch 6/200
450/450 [==============================] - 1s 3ms/step - loss: 0.1516
Epoch 7/200
450/450 [==============================] - 1s 3ms/step - loss: 0.1357
Epoch 8/200
450/450 [==============================] - 1s 3ms/step - loss: 0.1310
Epoch 9/200
450/450 [==============================] - 1s 3ms/step - loss: 0.1272
Epoch 10/200
450/450 [==============================] - 2s 4ms/step - loss: 0.1209
Epoch 11/200
450/450 [==============================] - 2s 3ms/step - loss: 0.1177
Epoch 12/200
450/450 [==============================] - 1s 3ms/step - loss: 0.1138
Epoch 13/200
450/450 [==============================] - 1s 3ms/step - loss: 0.1122
Epoch 14/200
450/450 [==============================] - 1s 3ms/step - loss: 0.1092
Epoch 15/200
450/450 [==============================] - 1s 3ms/step - loss: 0.1095
Epoch 16/200
450/450 [==============================] - 1s 3ms/step - loss: 0.1071
Epoch 17/200
450/450 [==============================] - 1s 3ms/step - loss: 0.1035
Epoch 18/200
450/450 [==============================] - 1s 3ms/step - loss: 0.1037
Epoch 19/200
450/450 [==============================] - 1s 3ms/step - loss: 0.1046
Epoch 20/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0996
Epoch 21/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0991
Epoch 22/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0989
Epoch 23/200
450/450 [==============================] - 2s 4ms/step - loss: 0.0974
Epoch 24/200
450/450 [==============================] - 2s 4ms/step - loss: 0.0972
Epoch 25/200
450/450 [==============================] - 2s 4ms/step - loss: 0.0963
Epoch 26/200
450/450 [==============================] - 2s 4ms/step - loss: 0.0962
Epoch 27/200
450/450 [==============================] - 2s 4ms/step - loss: 0.0964
Epoch 28/200
450/450 [==============================] - 2s 4ms/step - loss: 0.0959
Epoch 29/200
450/450 [==============================] - 2s 4ms/step - loss: 0.0954
Epoch 30/200
450/450 [==============================] - 2s 4ms/step - loss: 0.0939
Epoch 31/200
450/450 [==============================] - 2s 3ms/step - loss: 0.0947
Epoch 32/200
450/450 [==============================] - 2s 3ms/step - loss: 0.0939
Epoch 33/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0938
Epoch 34/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0944
Epoch 35/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0932
Epoch 36/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0917
Epoch 37/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0922
Epoch 38/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0919
Epoch 39/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0928
Epoch 40/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0906
Epoch 41/200
450/450 [==============================] - 2s 3ms/step - loss: 0.0915
Epoch 42/200
450/450 [==============================] - 2s 3ms/step - loss: 0.0914
Epoch 43/200
450/450 [==============================] - 2s 4ms/step - loss: 0.0912
Epoch 44/200
450/450 [==============================] - 2s 3ms/step - loss: 0.0899
Epoch 45/200
450/450 [==============================] - 2s 3ms/step - loss: 0.0900
Epoch 46/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0896
Epoch 47/200
450/450 [==============================] - 2s 3ms/step - loss: 0.0898
Epoch 48/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0907
Epoch 49/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0899
Epoch 50/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0893
Epoch 51/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0891
Epoch 52/200
450/450 [==============================] - 2s 3ms/step - loss: 0.0879
Epoch 53/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0880
Epoch 54/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0883
Epoch 55/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0885
Epoch 56/200
450/450 [==============================] - 2s 3ms/step - loss: 0.0883
Epoch 57/200
450/450 [==============================] - 2s 4ms/step - loss: 0.0882
Epoch 58/200
450/450 [==============================] - 2s 3ms/step - loss: 0.0890
Epoch 59/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0880
Epoch 60/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0881
Epoch 61/200
450/450 [==============================] - 2s 4ms/step - loss: 0.0883
Epoch 62/200
450/450 [==============================] - 2s 3ms/step - loss: 0.0876
Epoch 63/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0869
Epoch 64/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0875
Epoch 65/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0869
Epoch 66/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0865
Epoch 67/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0875
Epoch 68/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0869
Epoch 69/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0869
Epoch 70/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0869
Epoch 71/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0861
Epoch 72/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0876
Epoch 73/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0880
Epoch 74/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0860
Epoch 75/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0861
Epoch 76/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0862
Epoch 77/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0855
Epoch 78/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0862
Epoch 79/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0854
Epoch 80/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0861
Epoch 81/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0864
Epoch 82/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0863
Epoch 83/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0857
Epoch 84/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0858
Epoch 85/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0849
Epoch 86/200
450/450 [==============================] - 2s 3ms/step - loss: 0.0852
Epoch 87/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0848
Epoch 88/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0852
Epoch 89/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0858
Epoch 90/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0854
Epoch 91/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0854
Epoch 92/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0853
Epoch 93/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0848
Epoch 94/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0844
Epoch 95/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0845
Epoch 96/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0840
Epoch 97/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0846
Epoch 98/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0852
Epoch 99/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0840
Epoch 100/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0846
Epoch 101/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0848
Epoch 102/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0845
Epoch 103/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0846
Epoch 104/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0843
Epoch 105/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0840
Epoch 106/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0837
Epoch 107/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0844
Epoch 108/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0844
Epoch 109/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0837
Epoch 110/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0844
Epoch 111/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0834
Epoch 112/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0834
Epoch 113/200
450/450 [==============================] - 2s 4ms/step - loss: 0.0838
Epoch 114/200
450/450 [==============================] - 2s 4ms/step - loss: 0.0837
Epoch 115/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0840
Epoch 116/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0837
Epoch 117/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0831
Epoch 118/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0837
Epoch 119/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0840
Epoch 120/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0839
Epoch 121/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0830
Epoch 122/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0829
Epoch 123/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0830
Epoch 124/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0828
Epoch 125/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0837
Epoch 126/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0838
Epoch 127/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0831
Epoch 128/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0830
Epoch 129/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0827
Epoch 130/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0828
Epoch 131/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0830
Epoch 132/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0827
Epoch 133/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0823
Epoch 134/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0820
Epoch 135/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0827
Epoch 136/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0828
Epoch 137/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0833
Epoch 138/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0828
Epoch 139/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0826
Epoch 140/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0826
Epoch 141/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0827
Epoch 142/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0830
Epoch 143/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0821
Epoch 144/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0821
Epoch 145/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0819
Epoch 146/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0822
Epoch 147/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0821
Epoch 148/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0817
Epoch 149/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0828
Epoch 150/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0822
Epoch 151/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0821
Epoch 152/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0816
Epoch 153/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0821
Epoch 154/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0819
Epoch 155/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0816
Epoch 156/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0814
Epoch 157/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0818
Epoch 158/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0815
Epoch 159/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0819
Epoch 160/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0822
Epoch 161/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0812
Epoch 162/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0814
Epoch 163/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0816
Epoch 164/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0818
Epoch 165/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0812
Epoch 166/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0820
Epoch 167/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0813
Epoch 168/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0816
Epoch 169/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0812
Epoch 170/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0819
Epoch 171/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0814
Epoch 172/200
450/450 [==============================] - 2s 3ms/step - loss: 0.0815
Epoch 173/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0813
Epoch 174/200
450/450 [==============================] - 2s 3ms/step - loss: 0.0806
Epoch 175/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0805
Epoch 176/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0812
Epoch 177/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0805
Epoch 178/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0806
Epoch 179/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0807
Epoch 180/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0808
Epoch 181/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0806
Epoch 182/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0809
Epoch 183/200
450/450 [==============================] - 2s 4ms/step - loss: 0.0803
Epoch 184/200
450/450 [==============================] - 2s 4ms/step - loss: 0.0807
Epoch 185/200
450/450 [==============================] - 2s 4ms/step - loss: 0.0806
Epoch 186/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0808
Epoch 187/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0804
Epoch 188/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0802
Epoch 189/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0803
Epoch 190/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0805
Epoch 191/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0805
Epoch 192/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0805
Epoch 193/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0807
Epoch 194/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0800
Epoch 195/200
450/450 [==============================] - 2s 3ms/step - loss: 0.0806
Epoch 196/200
450/450 [==============================] - 2s 3ms/step - loss: 0.0802
Epoch 197/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0803
Epoch 198/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0806
Epoch 199/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0800
Epoch 200/200
450/450 [==============================] - 1s 3ms/step - loss: 0.0799
1/1 [==============================] - 0s 198ms/step
Model Number: 252 with model LastValueNaive in generation 1 of 1
Model Number: 253 with model MetricMotif in generation 1 of 1
Model Number: 254 with model MetricMotif in generation 1 of 1
Model Number: 255 with model DatepartRegression in generation 1 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Template Eval Error: TypeError('Cannot subtract tz-naive and tz-aware datetime-like objects') in model 255 in generation 1: DatepartRegression
Model Number: 256 with model MAR in generation 1 of 1
Model Number: 257 with model FFT in generation 1 of 1
Model Number: 258 with model SeasonalityMotif in generation 1 of 1
Model Number: 259 with model ETS in generation 1 of 1
Model Number: 260 with model AverageValueNaive in generation 1 of 1
Model Number: 261 with model LastValueNaive in generation 1 of 1
Model Number: 262 with model MetricMotif in generation 1 of 1
Model Number: 263 with model BallTreeMultivariateMotif in generation 1 of 1
Model Number: 264 with model SeasonalNaive in generation 1 of 1
Model Number: 265 with model KalmanStateSpace in generation 1 of 1
Model Number: 266 with model RRVAR in generation 1 of 1
Model Number: 267 with model ConstantNaive in generation 1 of 1
Model Number: 268 with model ARIMA in generation 1 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/tools/transform.py:2411: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  return (df - self.means.shift(self.lag).values[..., None]).fillna(
 This problem is unconstrained.

RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =           13     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  1.30828D+01    |proj g|=  2.81733D+00

At iterate    1    f=  1.17124D+01    |proj g|=  6.61569D-02

At iterate    2    f=  1.17045D+01    |proj g|=  4.53266D-02

At iterate    3    f=  1.16974D+01    |proj g|=  1.91695D-02

At iterate    4    f=  1.16963D+01    |proj g|=  1.63694D-02

At iterate    5    f=  1.16953D+01    |proj g|=  1.18444D-02

At iterate    6    f=  1.16943D+01    |proj g|=  6.58422D-03

At iterate    7    f=  1.16940D+01    |proj g|=  1.80774D-03

At iterate    8    f=  1.16939D+01    |proj g|=  2.06827D-03

At iterate    9    f=  1.16939D+01    |proj g|=  1.88223D-03

At iterate   10    f=  1.16939D+01    |proj g|=  8.76633D-04

At iterate   11    f=  1.16939D+01    |proj g|=  3.30863D-04

At iterate   12    f=  1.16938D+01    |proj g|=  2.71977D-04

At iterate   13    f=  1.16938D+01    |proj g|=  1.71733D-04

At iterate   14    f=  1.16938D+01    |proj g|=  5.14706D-05

At iterate   15    f=  1.16938D+01    |proj g|=  2.85382D-05

At iterate   16    f=  1.16938D+01    |proj g|=  2.77012D-05

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
   13     16     19      1     0     0   2.770D-05   1.169D+01
  F =   11.693846394755534

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
Template Eval Error: Exception('Transformer AlignLastValue failed on inverse') in model 268 in generation 1: ARIMA
Model Number: 269 with model MultivariateMotif in generation 1 of 1
Model Number: 270 with model UnivariateMotif in generation 1 of 1
Model Number: 271 with model GLS in generation 1 of 1
Model Number: 272 with model LastValueNaive in generation 1 of 1
Model Number: 273 with model KalmanStateSpace in generation 1 of 1
Model Number: 274 with model LastValueNaive in generation 1 of 1
Model Number: 275 with model DatepartRegression in generation 1 of 1
Model Number: 276 with model AverageValueNaive in generation 1 of 1
Model Number: 277 with model NVAR in generation 1 of 1
Model Number: 278 with model LastValueNaive in generation 1 of 1
Model Number: 279 with model SeasonalNaive in generation 1 of 1
Model Number: 280 with model KalmanStateSpace in generation 1 of 1
Model Number: 281 with model UnobservedComponents in generation 1 of 1
Model Number: 282 with model Theta in generation 1 of 1
Model Number: 283 with model LastValueNaive in generation 1 of 1
Model Number: 284 with model SeasonalityMotif in generation 1 of 1
Template Eval Error: TypeError('Cannot subtract tz-naive and tz-aware datetime-like objects') in model 284 in generation 1: SeasonalityMotif
Model Number: 285 with model Cassandra in generation 1 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/models/cassandra.py:1177: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  first_adjust.iloc[0] = 0.5

Model Number: 286 with model ETS in generation 1 of 1
Template Eval Error: ValueError("Model returned NaN due to a preprocessing transformer {'fillna': 'ffill', 'transformations': {'0': 'cffilter', '1': 'AlignLastValue', '2': 'AlignLastValue'}, 'transformation_params': {'0': {}, '1': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False}, '2': {'rows': 7, 'lag': 1, 'method': 'multiplicative', 'strength': 1.0, 'first_value_only': False}}}. fail_on_forecast_nan=True") in model 286 in generation 1: ETS
Model Number: 287 with model RRVAR in generation 1 of 1
Template Eval Error: Exception('Transformer KalmanSmoothing failed on fit') in model 287 in generation 1: RRVAR
Model Number: 288 with model AverageValueNaive in generation 1 of 1
Model Number: 289 with model RRVAR in generation 1 of 1
Template Eval Error: LinAlgError('SVD did not converge') in model 289 in generation 1: RRVAR
Model Number: 290 with model NVAR in generation 1 of 1
Model Number: 291 with model FFT in generation 1 of 1
Model Number: 292 with model ConstantNaive in generation 1 of 1
Model Number: 293 with model WindowRegression in generation 1 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/linalg/linalg.py:2027: RuntimeWarning: overflow encountered in divide
  s = divide(1, s, where=large, out=s)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/linalg/linalg.py:2030: RuntimeWarning: invalid value encountered in matmul
  res = matmul(transpose(vt), multiply(s[..., newaxis], transpose(u)))
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/models/matrix_var.py:29: RuntimeWarning: invalid value encountered in matmul
  W = X2 @ np.linalg.pinv((V @ X1))

Model Number: 294 with model LastValueNaive in generation 1 of 1
Model Number: 295 with model GLM in generation 1 of 1
Model Number: 296 with model MultivariateMotif in generation 1 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

Model Number: 297 with model MultivariateMotif in generation 1 of 1
Model Number: 298 with model FFT in generation 1 of 1
Model Number: 299 with model FFT in generation 1 of 1
Model Number: 300 with model KalmanStateSpace in generation 1 of 1
Model Number: 301 with model SeasonalNaive in generation 1 of 1
Model Number: 302 with model AverageValueNaive in generation 1 of 1
Model Number: 303 with model UnobservedComponents in generation 1 of 1
Model Number: 304 with model SeasonalNaive in generation 1 of 1
Model Number: 305 with model SeasonalityMotif in generation 1 of 1
Model Number: 306 with model SeasonalNaive in generation 1 of 1
Model Number: 307 with model UnobservedComponents in generation 1 of 1
Model Number: 308 with model SeasonalNaive in generation 1 of 1
Template Eval Error: Exception('Transformer RegressionFilter failed on fit') in model 308 in generation 1: SeasonalNaive
Model Number: 309 with model GLS in generation 1 of 1
Model Number: 310 with model SeasonalNaive in generation 1 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=7.4395e-27): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

Model Number: 311 with model Theta in generation 1 of 1
Model Number: 312 with model WindowRegression in generation 1 of 1
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 312 in generation 1: WindowRegression
Model Number: 313 with model ARDL in generation 1 of 1
Model Number: 314 with model NVAR in generation 1 of 1
Model Number: 315 with model GLS in generation 1 of 1
Model Number: 316 with model SectionalMotif in generation 1 of 1
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 316 in generation 1: SectionalMotif
Model Number: 317 with model WindowRegression in generation 1 of 1
Template Eval Error: ModuleNotFoundError("No module named 'lightgbm'") in model 317 in generation 1: WindowRegression
Model Number: 318 with model SeasonalityMotif in generation 1 of 1
Template Eval Error: TypeError('Cannot subtract tz-naive and tz-aware datetime-like objects') in model 318 in generation 1: SeasonalityMotif
Model Number: 319 with model MetricMotif in generation 1 of 1
Template Eval Error: Exception('Transformer AlignLastValue failed on inverse') in model 319 in generation 1: MetricMotif
Model Number: 320 with model RRVAR in generation 1 of 1
Model Number: 321 with model ConstantNaive in generation 1 of 1
Model Number: 322 with model Cassandra in generation 1 of 1
Template Eval Error: ValueError('Only gave one variable to VAR') in model 322 in generation 1: Cassandra
Model Number: 323 with model RRVAR in generation 1 of 1
Model Number: 324 with model DatepartRegression in generation 1 of 1
Model Number: 325 with model ConstantNaive in generation 1 of 1
Model Number: 326 with model Theta in generation 1 of 1
Model Number: 327 with model UnobservedComponents in generation 1 of 1
Model Number: 328 with model SeasonalNaive in generation 1 of 1
Model Number: 329 with model SeasonalityMotif in generation 1 of 1
Template Eval Error: TypeError('Cannot subtract tz-naive and tz-aware datetime-like objects') in model 329 in generation 1: SeasonalityMotif
Model Number: 330 with model AverageValueNaive in generation 1 of 1
Model Number: 331 with model SectionalMotif in generation 1 of 1
Model Number: 332 with model WindowRegression in generation 1 of 1
Epoch 1/50
5/5 [==============================] - 1s 6ms/step - loss: 174647.3281
Epoch 2/50
5/5 [==============================] - 0s 4ms/step - loss: 174646.2500
Epoch 3/50
5/5 [==============================] - 0s 4ms/step - loss: 174645.2031
Epoch 4/50
5/5 [==============================] - 0s 3ms/step - loss: 174644.5000
Epoch 5/50
5/5 [==============================] - 0s 3ms/step - loss: 174644.0000
Epoch 6/50
5/5 [==============================] - 0s 3ms/step - loss: 174643.5625
Epoch 7/50
5/5 [==============================] - 0s 3ms/step - loss: 174643.1719
Epoch 8/50
5/5 [==============================] - 0s 3ms/step - loss: 174642.7812
Epoch 9/50
5/5 [==============================] - 0s 3ms/step - loss: 174642.3906
Epoch 10/50
5/5 [==============================] - 0s 3ms/step - loss: 174642.0156
Epoch 11/50
5/5 [==============================] - 0s 3ms/step - loss: 174641.6406
Epoch 12/50
5/5 [==============================] - 0s 3ms/step - loss: 174641.2656
Epoch 13/50
5/5 [==============================] - 0s 3ms/step - loss: 174640.9062
Epoch 14/50
5/5 [==============================] - 0s 4ms/step - loss: 174640.5312
Epoch 15/50
5/5 [==============================] - 0s 3ms/step - loss: 174640.1719
Epoch 16/50
5/5 [==============================] - 0s 3ms/step - loss: 174639.8125
Epoch 17/50
5/5 [==============================] - 0s 4ms/step - loss: 174639.4219
Epoch 18/50
5/5 [==============================] - 0s 3ms/step - loss: 174639.0625
Epoch 19/50
5/5 [==============================] - 0s 4ms/step - loss: 174638.6875
Epoch 20/50
5/5 [==============================] - 0s 4ms/step - loss: 174638.3438
Epoch 21/50
5/5 [==============================] - 0s 4ms/step - loss: 174637.9688
Epoch 22/50
5/5 [==============================] - 0s 3ms/step - loss: 174637.6094
Epoch 23/50
5/5 [==============================] - 0s 3ms/step - loss: 174637.2500
Epoch 24/50
5/5 [==============================] - 0s 4ms/step - loss: 174636.8594
Epoch 25/50
5/5 [==============================] - 0s 4ms/step - loss: 174636.5000
Epoch 26/50
5/5 [==============================] - 0s 3ms/step - loss: 174636.1562
Epoch 27/50
5/5 [==============================] - 0s 3ms/step - loss: 174635.7969
Epoch 28/50
5/5 [==============================] - 0s 3ms/step - loss: 174635.4219
Epoch 29/50
5/5 [==============================] - 0s 3ms/step - loss: 174635.0625
Epoch 30/50
5/5 [==============================] - 0s 3ms/step - loss: 174634.6719
Epoch 31/50
5/5 [==============================] - 0s 3ms/step - loss: 174634.3125
Epoch 32/50
5/5 [==============================] - 0s 3ms/step - loss: 174633.9531
Epoch 33/50
5/5 [==============================] - 0s 3ms/step - loss: 174633.5938
Epoch 34/50
5/5 [==============================] - 0s 4ms/step - loss: 174633.2344
Epoch 35/50
5/5 [==============================] - 0s 3ms/step - loss: 174632.8594
Epoch 36/50
5/5 [==============================] - 0s 3ms/step - loss: 174632.4844
Epoch 37/50
5/5 [==============================] - 0s 3ms/step - loss: 174632.1406
Epoch 38/50
5/5 [==============================] - 0s 4ms/step - loss: 174631.7656
Epoch 39/50
5/5 [==============================] - 0s 3ms/step - loss: 174631.4062
Epoch 40/50
5/5 [==============================] - 0s 3ms/step - loss: 174631.0469
Epoch 41/50
5/5 [==============================] - 0s 3ms/step - loss: 174630.6875
Epoch 42/50
5/5 [==============================] - 0s 3ms/step - loss: 174630.3125
Epoch 43/50
5/5 [==============================] - 0s 3ms/step - loss: 174629.9375
Epoch 44/50
5/5 [==============================] - 0s 3ms/step - loss: 174629.5781
Epoch 45/50
5/5 [==============================] - 0s 3ms/step - loss: 174629.2031
Epoch 46/50
5/5 [==============================] - 0s 4ms/step - loss: 174628.8438
Epoch 47/50
5/5 [==============================] - 0s 3ms/step - loss: 174628.4844
Epoch 48/50
5/5 [==============================] - 0s 3ms/step - loss: 174628.1094
Epoch 49/50
5/5 [==============================] - 0s 3ms/step - loss: 174627.7500
Epoch 50/50
5/5 [==============================] - 0s 3ms/step - loss: 174627.3750
WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x29380d800> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
1/1 [==============================] - 0s 283ms/step
Model Number: 333 with model LastValueNaive in generation 1 of 1
Model Number: 334 with model LastValueNaive in generation 1 of 1
Model Number: 335 with model MultivariateMotif in generation 1 of 1
Model Number: 336 with model Theta in generation 1 of 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Model Number: 337 with model KalmanStateSpace in generation 1 of 1
Model Number: 338 with model ConstantNaive in generation 1 of 1
Model Number: 339 with model GLM in generation 1 of 1
Model Number: 340 with model MultivariateMotif in generation 1 of 1
Model Number: 341 with model GLS in generation 1 of 1
Model Number: 342 with model UnobservedComponents in generation 1 of 1
Template Eval Error: ValueError("regression_type='User' but no future_regressor supplied") in model 342 in generation 1: UnobservedComponents
Model Number: 343 with model BallTreeMultivariateMotif in generation 1 of 1
Model Number: 344 with model Ensemble in generation 2 of Ensembles
Model Number: 345 with model Ensemble in generation 2 of Ensembles
Model Number: 346 with model Ensemble in generation 2 of Ensembles
Model Number: 347 with model Ensemble in generation 2 of Ensembles
Model Number: 348 with model Ensemble in generation 2 of Ensembles
Model Number: 349 with model Ensemble in generation 2 of Ensembles
Model Number: 350 with model Ensemble in generation 2 of Ensembles
Model Number: 351 with model Ensemble in generation 2 of Ensembles
Validation Round: 1
Model Number: 1 of 53 with model MultivariateMotif for Validation 1
📈 1 - MultivariateMotif with avg smape 37.13:
Model Number: 2 of 53 with model Ensemble for Validation 1
📈 2 - Ensemble with avg smape 30.44:
Model Number: 3 of 53 with model Ensemble for Validation 1
📈 3 - Ensemble with avg smape 27.07:
Model Number: 4 of 53 with model Ensemble for Validation 1
📈 4 - Ensemble with avg smape 26.81:
Model Number: 5 of 53 with model SeasonalityMotif for Validation 1
📈 5 - SeasonalityMotif with avg smape 13.43:
Model Number: 6 of 53 with model SeasonalityMotif for Validation 1
6 - SeasonalityMotif with avg smape 87.73:
Model Number: 7 of 53 with model AverageValueNaive for Validation 1
7 - AverageValueNaive with avg smape 44.22:
Model Number: 8 of 53 with model Theta for Validation 1
8 - Theta with avg smape 44.29:
Model Number: 9 of 53 with model UnivariateMotif for Validation 1
9 - UnivariateMotif with avg smape 81.84:
Model Number: 10 of 53 with model NVAR for Validation 1
10 - NVAR with avg smape 32.39:
Model Number: 11 of 53 with model AverageValueNaive for Validation 1
11 - AverageValueNaive with avg smape 43.28:
Model Number: 12 of 53 with model MultivariateMotif for Validation 1
12 - MultivariateMotif with avg smape 43.12:
Model Number: 13 of 53 with model ConstantNaive for Validation 1
13 - ConstantNaive with avg smape 43.28:
Model Number: 14 of 53 with model ConstantNaive for Validation 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.388e+13, tolerance: 6.935e+09
  model = cd_fast.enet_coordinate_descent(

14 - ConstantNaive with avg smape 43.28:
Model Number: 15 of 53 with model ConstantNaive for Validation 1
15 - ConstantNaive with avg smape 43.28:
Model Number: 16 of 53 with model AverageValueNaive for Validation 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.388e+13, tolerance: 6.935e+09
  model = cd_fast.enet_coordinate_descent(

16 - AverageValueNaive with avg smape 69.98:
Model Number: 17 of 53 with model SeasonalityMotif for Validation 1
17 - SeasonalityMotif with avg smape 59.5:
Model Number: 18 of 53 with model BallTreeMultivariateMotif for Validation 1
📈 18 - BallTreeMultivariateMotif with avg smape 10.9:
Model Number: 19 of 53 with model MultivariateMotif for Validation 1
19 - MultivariateMotif with avg smape 12.05:
Model Number: 20 of 53 with model LastValueNaive for Validation 1
20 - LastValueNaive with avg smape 43.28:
Model Number: 21 of 53 with model LastValueNaive for Validation 1
21 - LastValueNaive with avg smape 43.28:
Model Number: 22 of 53 with model GLS for Validation 1
22 - GLS with avg smape 43.28:
Model Number: 23 of 53 with model GLS for Validation 1
23 - GLS with avg smape 43.28:
Model Number: 24 of 53 with model BallTreeMultivariateMotif for Validation 1
24 - BallTreeMultivariateMotif with avg smape 79.24:
Model Number: 25 of 53 with model DatepartRegression for Validation 1
25 - DatepartRegression with avg smape 20.28:
Model Number: 26 of 53 with model FFT for Validation 1
26 - FFT with avg smape 67.52:
Model Number: 27 of 53 with model KalmanStateSpace for Validation 1
27 - KalmanStateSpace with avg smape 23.59:
Model Number: 28 of 53 with model KalmanStateSpace for Validation 1
28 - KalmanStateSpace with avg smape 43.28:
Model Number: 29 of 53 with model MetricMotif for Validation 1
29 - MetricMotif with avg smape 16.15:
Model Number: 30 of 53 with model SeasonalNaive for Validation 1
30 - SeasonalNaive with avg smape 94.46:
Model Number: 31 of 53 with model KalmanStateSpace for Validation 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

31 - KalmanStateSpace with avg smape 57.75:
Model Number: 32 of 53 with model DatepartRegression for Validation 1
Epoch 1/50
449/449 [==============================] - 2s 1ms/step - loss: 0.3216
Epoch 2/50
449/449 [==============================] - 0s 1ms/step - loss: 0.2855
Epoch 3/50
449/449 [==============================] - 0s 1ms/step - loss: 0.2708
Epoch 4/50
449/449 [==============================] - 0s 1ms/step - loss: 0.2354
Epoch 5/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1903
Epoch 6/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1565
Epoch 7/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1444
Epoch 8/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1352
Epoch 9/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1292
Epoch 10/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1248
Epoch 11/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1212
Epoch 12/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1165
Epoch 13/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1146
Epoch 14/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1153
Epoch 15/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1125
Epoch 16/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1088
Epoch 17/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1065
Epoch 18/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1044
Epoch 19/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1032
Epoch 20/50
449/449 [==============================] - 1s 1ms/step - loss: 0.1020
Epoch 21/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0993
Epoch 22/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0985
Epoch 23/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0990
Epoch 24/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0945
Epoch 25/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0945
Epoch 26/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0939
Epoch 27/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0931
Epoch 28/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0906
Epoch 29/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0894
Epoch 30/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0884
Epoch 31/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0872
Epoch 32/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0852
Epoch 33/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0856
Epoch 34/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0825
Epoch 35/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0831
Epoch 36/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0832
Epoch 37/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0814
Epoch 38/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0798
Epoch 39/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0802
Epoch 40/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0790
Epoch 41/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0777
Epoch 42/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0763
Epoch 43/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0755
Epoch 44/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0737
Epoch 45/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0753
Epoch 46/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0734
Epoch 47/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0736
Epoch 48/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0738
Epoch 49/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0720
Epoch 50/50
449/449 [==============================] - 0s 1ms/step - loss: 0.0719
WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x2eb98a5c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
1/1 [==============================] - 0s 268ms/step
📈 32 - DatepartRegression with avg smape 6.16:
Model Number: 33 of 53 with model LastValueNaive for Validation 1
33 - LastValueNaive with avg smape 43.28:
Model Number: 34 of 53 with model Theta for Validation 1
34 - Theta with avg smape 43.28:
Model Number: 35 of 53 with model DatepartRegression for Validation 1
35 - DatepartRegression with avg smape 15.22:
Model Number: 36 of 53 with model MetricMotif for Validation 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

36 - MetricMotif with avg smape 9.61:
Model Number: 37 of 53 with model Cassandra for Validation 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autots/models/cassandra.py:1177: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  first_adjust.iloc[0] = 0.5

37 - Cassandra with avg smape 37.66:
Model Number: 38 of 53 with model SeasonalNaive for Validation 1
38 - SeasonalNaive with avg smape 42.08:
Model Number: 39 of 53 with model SeasonalNaive for Validation 1
39 - SeasonalNaive with avg smape 43.76:
Model Number: 40 of 53 with model WindowRegression for Validation 1
40 - WindowRegression with avg smape 45.47:
Model Number: 41 of 53 with model UnobservedComponents for Validation 1
41 - UnobservedComponents with avg smape 23.59:
Model Number: 42 of 53 with model UnobservedComponents for Validation 1
42 - UnobservedComponents with avg smape 43.41:
Model Number: 43 of 53 with model SectionalMotif for Validation 1
43 - SectionalMotif with avg smape 54.14:
Model Number: 44 of 53 with model UnobservedComponents for Validation 1
44 - UnobservedComponents with avg smape 37.67:
Model Number: 45 of 53 with model ARDL for Validation 1
45 - ARDL with avg smape 8.98:
Model Number: 46 of 53 with model FFT for Validation 1
46 - FFT with avg smape 43.22:
Model Number: 47 of 53 with model GLS for Validation 1
47 - GLS with avg smape 83.88:
Model Number: 48 of 53 with model ETS for Validation 1
48 - ETS with avg smape 43.28:
Model Number: 49 of 53 with model ETS for Validation 1
49 - ETS with avg smape 43.3:
Model Number: 50 of 53 with model ETS for Validation 1
50 - ETS with avg smape 69.98:
Model Number: 51 of 53 with model GLM for Validation 1
51 - GLM with avg smape 43.28:
Model Number: 52 of 53 with model ARDL for Validation 1
52 - ARDL with avg smape 21.05:
Model Number: 53 of 53 with model MetricMotif for Validation 1
53 - MetricMotif with avg smape 22.38:
Model Number: 405 with model Ensemble in generation 3 of Ensembles
Model Number: 406 with model Ensemble in generation 3 of Ensembles
Epoch 1/50
450/450 [==============================] - 2s 1ms/step - loss: 0.3209
Epoch 2/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2874
Epoch 3/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2762
Epoch 4/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2551
Epoch 5/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2194
Epoch 6/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1756
Epoch 7/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1431
Epoch 8/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1320
Epoch 9/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1286
Epoch 10/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1240
Epoch 11/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1195
Epoch 12/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1166
Epoch 13/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1130
Epoch 14/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1114
Epoch 15/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1095
Epoch 16/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1099
Epoch 17/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1062
Epoch 18/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1047
Epoch 19/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1051
Epoch 20/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1021
Epoch 21/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1013
Epoch 22/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1013
Epoch 23/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1002
Epoch 24/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0990
Epoch 25/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0973
Epoch 26/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0971
Epoch 27/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0970
Epoch 28/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0945
Epoch 29/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0941
Epoch 30/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0931
Epoch 31/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0930
Epoch 32/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0917
Epoch 33/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0907
Epoch 34/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0905
Epoch 35/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0889
Epoch 36/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0874
Epoch 37/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0880
Epoch 38/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0864
Epoch 39/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0849
Epoch 40/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0829
Epoch 41/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0821
Epoch 42/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0811
Epoch 43/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0798
Epoch 44/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0780
Epoch 45/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0771
Epoch 46/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0766
Epoch 47/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0767
Epoch 48/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0754
Epoch 49/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0746
Epoch 50/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0737
1/1 [==============================] - 0s 269ms/step
Model Number: 407 with model Ensemble in generation 3 of Ensembles
Epoch 1/50
450/450 [==============================] - 2s 1ms/step - loss: 0.3242
Epoch 2/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2875
Epoch 3/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2627
Epoch 4/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2192
Epoch 5/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1738
Epoch 6/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1511
Epoch 7/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1392
Epoch 8/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1278
Epoch 9/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1235
Epoch 10/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1187
Epoch 11/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1153
Epoch 12/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1125
Epoch 13/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1086
Epoch 14/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1064
Epoch 15/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1062
Epoch 16/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1037
Epoch 17/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1018
Epoch 18/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0994
Epoch 19/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0971
Epoch 20/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0959
Epoch 21/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0917
Epoch 22/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0933
Epoch 23/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0916
Epoch 24/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0901
Epoch 25/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0888
Epoch 26/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0874
Epoch 27/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0865
Epoch 28/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0855
Epoch 29/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0840
Epoch 30/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0836
Epoch 31/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0830
Epoch 32/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0808
Epoch 33/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0805
Epoch 34/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0807
Epoch 35/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0787
Epoch 36/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0778
Epoch 37/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0778
Epoch 38/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0749
Epoch 39/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0754
Epoch 40/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0734
Epoch 41/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0740
Epoch 42/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0721
Epoch 43/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0710
Epoch 44/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0706
Epoch 45/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0698
Epoch 46/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0695
Epoch 47/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0687
Epoch 48/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0668
Epoch 49/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0655
Epoch 50/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0668
1/1 [==============================] - 0s 269ms/step
Model Number: 408 with model Ensemble in generation 3 of Ensembles
Epoch 1/50
450/450 [==============================] - 2s 1ms/step - loss: 0.3191
Epoch 2/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2850
Epoch 3/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2705
Epoch 4/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2483
Epoch 5/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2000
Epoch 6/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1573
Epoch 7/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1404
Epoch 8/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1322
Epoch 9/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1307
Epoch 10/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1292
Epoch 11/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1237
Epoch 12/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1205
Epoch 13/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1196
Epoch 14/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1162
Epoch 15/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1145
Epoch 16/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1151
Epoch 17/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1109
Epoch 18/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1096
Epoch 19/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1091
Epoch 20/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1058
Epoch 21/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1042
Epoch 22/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1044
Epoch 23/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1026
Epoch 24/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1003
Epoch 25/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0991
Epoch 26/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0978
Epoch 27/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0963
Epoch 28/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0948
Epoch 29/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0938
Epoch 30/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0916
Epoch 31/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0910
Epoch 32/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0901
Epoch 33/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0885
Epoch 34/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0903
Epoch 35/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0870
Epoch 36/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0845
Epoch 37/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0856
Epoch 38/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0821
Epoch 39/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0808
Epoch 40/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0807
Epoch 41/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0786
Epoch 42/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0773
Epoch 43/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0768
Epoch 44/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0756
Epoch 45/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0734
Epoch 46/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0728
Epoch 47/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0708
Epoch 48/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0703
Epoch 49/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0696
Epoch 50/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0682
1/1 [==============================] - 0s 269ms/step
Model Number: 409 with model Ensemble in generation 3 of Ensembles
Model Number: 410 with model Ensemble in generation 3 of Ensembles
Epoch 1/50
450/450 [==============================] - 2s 1ms/step - loss: 0.3279
Epoch 2/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2921
Epoch 3/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2749
Epoch 4/50
450/450 [==============================] - 0s 1ms/step - loss: 0.2396
Epoch 5/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1856
Epoch 6/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1503
Epoch 7/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1396
Epoch 8/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1311
Epoch 9/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1277
Epoch 10/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1248
Epoch 11/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1201
Epoch 12/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1181
Epoch 13/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1151
Epoch 14/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1122
Epoch 15/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1100
Epoch 16/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1090
Epoch 17/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1071
Epoch 18/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1051
Epoch 19/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1036
Epoch 20/50
450/450 [==============================] - 0s 1ms/step - loss: 0.1012
Epoch 21/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0995
Epoch 22/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0990
Epoch 23/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0976
Epoch 24/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0957
Epoch 25/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0944
Epoch 26/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0924
Epoch 27/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0931
Epoch 28/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0902
Epoch 29/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0901
Epoch 30/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0883
Epoch 31/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0891
Epoch 32/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0868
Epoch 33/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0863
Epoch 34/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0860
Epoch 35/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0862
Epoch 36/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0849
Epoch 37/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0841
Epoch 38/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0827
Epoch 39/50
450/450 [==============================] - 1s 1ms/step - loss: 0.0826
Epoch 40/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0828
Epoch 41/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0813
Epoch 42/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0802
Epoch 43/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0801
Epoch 44/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0785
Epoch 45/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0775
Epoch 46/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0790
Epoch 47/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0784
Epoch 48/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0768
Epoch 49/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0763
Epoch 50/50
450/450 [==============================] - 0s 1ms/step - loss: 0.0748
1/1 [==============================] - 0s 268ms/step
Model Number: 411 with model Ensemble in generation 3 of Ensembles
Model Number: 412 with model Ensemble in generation 3 of Ensembles
Validation Round: 1
Model Number: 1 of 8 with model Ensemble for Validation 1
📈 1 - Ensemble with avg smape 7.71:
Model Number: 2 of 8 with model Ensemble for Validation 1
Epoch 1/50
449/449 [==============================] - 2s 1ms/step - loss: 0.3259
Epoch 2/50
449/449 [==============================] - 0s 1ms/step - loss: 0.2843
Epoch 3/50
449/449 [==============================] - 0s 1ms/step - loss: 0.2415
Epoch 4/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1797
Epoch 5/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1481
Epoch 6/50
449/449 [==============================] - 1s 1ms/step - loss: 0.1377
Epoch 7/50
449/449 [==============================] - 1s 1ms/step - loss: 0.1328
Epoch 8/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1250
Epoch 9/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1226
Epoch 10/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1190
Epoch 11/50
449/449 [==============================] - 1s 1ms/step - loss: 0.1153
Epoch 12/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1119
Epoch 13/50
449/449 [==============================] - 0s 1ms/step - loss: 0.1102
Epoch 14/50

In [57]:
print(model.best_model_name)
print(model.best_model_params)
print(model.best_model_transformation_params)

Ensemble
{'model_name': 'BestN', 'model_count': 3, 'model_metric': 'bestn_horizontal', 'models': {'17db5ee619a255b26be9fb18e03c43c2': {'Model': 'SeasonalityMotif', 'ModelParameters': '{"window": 5, "point_method": "weighted_mean", "distance_metric": "mse", "k": 10, "datepart_method": "expanded"}', 'TransformationParameters': '{"fillna": "ffill", "transformations": {"0": "AlignLastValue", "1": "AlignLastValue", "2": "AlignLastValue", "3": "ClipOutliers"}, "transformation_params": {"0": {"rows": 1, "lag": 1, "method": "additive", "strength": 1.0, "first_value_only": false}, "1": {"rows": 1, "lag": 1, "method": "additive", "strength": 1.0, "first_value_only": false}, "2": {"rows": 7, "lag": 1, "method": "multiplicative", "strength": 1.0, "first_value_only": false}, "3": {"method": "clip", "std_threshold": 3.5, "fillna": null}}}'}, 'a84c237628610389761aef3fe9b4928f': {'Model': 'BallTreeMultivariateMotif', 'ModelParameters': '{"window": 10, "point_method": "median", "distance_metric": "minkowski", "k": 10}', 'TransformationParameters': '{"fillna": "quadratic", "transformations": {"0": "AlignLastValue", "1": "AlignLastValue", "2": "ReplaceConstant"}, "transformation_params": {"0": {"rows": 1, "lag": 1, "method": "additive", "strength": 1.0, "first_value_only": false}, "1": {"rows": 1, "lag": 1, "method": "additive", "strength": 0.5, "first_value_only": false}, "2": {"constant": 0, "reintroduction_model": null, "fillna": "mean"}}}'}, '941e25f298f1bad1f7672bea5a5694db': {'Model': 'MetricMotif', 'ModelParameters': '{"window": 7, "point_method": "mean", "distance_metric": "euclidean", "k": 10, "comparison_transformation": {"fillna": "ffill", "transformations": {"0": null}, "transformation_params": {"0": {}}}, "combination_transformation": {"fillna": "rolling_mean", "transformations": {"0": "EWMAFilter"}, "transformation_params": {"0": {"span": 7}}}}', 'TransformationParameters': '{"fillna": "ffill", "transformations": {"0": "AlignLastValue", "1": "Detrend", "2": "RollingMeanTransformer", "3": "ClipOutliers"}, "transformation_params": {"0": {"rows": 1, "lag": 1, "method": "additive", "strength": 1.0, "first_value_only": false}, "1": {"model": "Linear", "phi": 1, "window": null, "transform_dict": {"fillna": null, "transformations": {"0": "bkfilter"}, "transformation_params": {"0": {}}}}, "2": {"fixed": true, "window": 3}, "3": {"method": "clip", "std_threshold": 3.5, "fillna": null}}}'}}, 'model_weights': {'17db5ee619a255b26be9fb18e03c43c2': 20.0, '941e25f298f1bad1f7672bea5a5694db': 19.0, 'a84c237628610389761aef3fe9b4928f': 18.0}, 'point_method': 'mean'}
{}

## Data2: Test data

In [4]:
data2 = pd.read_csv("cold-start-consumption-forecasting-test-data.csv", sep=";", parse_dates=['timestamp'])
data2

,obs_id,site_id,timestamp,temperature,temperature_-1,temperature_-2,load,load_-1,load_-2,target
0,2,78,2017-03-06 15:00:00-05:00,8.000000,8.933333,10.500000,5.245016e+05,5.504866e+05,6.558341e+05,5.133429e+05
1,13,78,2017-07-13 10:00:00-04:00,31.000000,30.000000,29.000000,1.262663e+06,1.245585e+06,1.265211e+06,1.191620e+06
2,16,78,2017-04-05 14:00:00-04:00,16.000000,16.800000,16.500000,6.293816e+05,7.560991e+05,9.208202e+05,7.175366e+05
3,24,78,2016-12-05 01:00:00-05:00,4.500000,6.000000,6.133333,6.502152e+05,5.204650e+05,3.412245e+05,6.782952e+05
4,30,78,2017-09-12 18:00:00-04:00,16.000000,16.000000,17.533333,6.814274e+05,7.720909e+05,8.267658e+05,6.585562e+05
...,...,...,...,...,...,...,...,...,...,...
5371,5326,91,2015-07-28 19:00:00-04:00,23.466667,24.220000,25.420000,1.924487e+03,1.893677e+03,1.936338e+03,0.000000e+00
5372,5353,91,2016-08-13 21:00:00-04:00,17.600000,18.783333,20.000000,1.476546e+03,1.491952e+03,1.520392e+03,0.000000e+00
5373,5354,91,2016-05-24 15:00:00-04:00,19.833333,21.333333,21.533333,1.540538e+03,1.750288e+03,2.842885e+03,0.000000e+00
5374,5360,91,2015-06-20 01:00:00-04:00,19.450000,19.516667,19.866667,1.944633e+03,1.947003e+03,1.976629e+03,0.000000e+00
5375,5364,91,2016-09-24 16:00:00-04:00,20.716667,22.420000,23.660000,1.546463e+03,1.558313e+03,1.618750e+03,0.000000e+00

In [5]:
data2.describe()

,obs_id,site_id,temperature,temperature_-1,temperature_-2,load,load_-1,load_-2,target
count,5376.000000,5376.000000,5376.000000,5376.000000,5376.000000,5.376000e+03,5.376000e+03,5.376000e+03,5.376000e+03
mean,2687.500000,84.500000,15.202782,15.191096,15.179296,8.154911e+04,8.183575e+04,8.205588e+04,1.023380e+04
std,1552.061854,4.031504,8.432832,8.421938,8.396866,1.932085e+05,1.941248e+05,1.949242e+05,7.220886e+04
min,0.000000,78.000000,-9.645455,-10.800000,-11.408333,3.644937e+01,3.617219e+01,3.617219e+01,0.000000e+00
25%,1343.750000,81.000000,8.531250,8.500000,8.729096,3.847368e+03,3.935141e+03,3.945115e+03,0.000000e+00
50%,2687.500000,84.500000,15.000000,15.025000,15.073864,1.397601e+04,1.377829e+04,1.378522e+04,0.000000e+00
75%,4031.250000,88.000000,21.500000,21.533333,21.566667,4.210523e+04,4.243047e+04,4.231121e+04,0.000000e+00
max,5375.000000,91.000000,37.500000,38.100000,36.000000,1.343137e+06,1.306128e+06,1.337277e+06,1.231521e+06

In [6]:
validation = data2[data2["target"] != 0]
validation

,obs_id,site_id,timestamp,temperature,temperature_-1,temperature_-2,load,load_-1,load_-2,target
0,2,78,2017-03-06 15:00:00-05:00,8.000000,8.933333,10.500000,5.245016e+05,5.504866e+05,6.558341e+05,5.133429e+05
1,13,78,2017-07-13 10:00:00-04:00,31.000000,30.000000,29.000000,1.262663e+06,1.245585e+06,1.265211e+06,1.191620e+06
2,16,78,2017-04-05 14:00:00-04:00,16.000000,16.800000,16.500000,6.293816e+05,7.560991e+05,9.208202e+05,7.175366e+05
3,24,78,2016-12-05 01:00:00-05:00,4.500000,6.000000,6.133333,6.502152e+05,5.204650e+05,3.412245e+05,6.782952e+05
4,30,78,2017-09-12 18:00:00-04:00,16.000000,16.000000,17.533333,6.814274e+05,7.720909e+05,8.267658e+05,6.585562e+05
...,...,...,...,...,...,...,...,...,...,...
5330,4621,90,2015-12-29 23:00:00-05:00,1.233333,2.000000,3.000000,1.337628e+04,1.883139e+04,2.256224e+04,2.057903e+04
5331,4644,90,2015-09-04 08:00:00-04:00,22.500000,21.066667,20.000000,9.678508e+04,3.182673e+04,1.775206e+04,7.645166e+04
5355,4996,91,2015-12-12 11:00:00-05:00,10.550000,11.733333,11.416667,4.424899e+03,3.588268e+03,2.794299e+03,3.058560e+03
5356,5009,91,2015-06-20 07:00:00-04:00,24.850000,23.216667,21.883333,2.232595e+03,2.102242e+03,1.996774e+03,2.306067e+03
5357,5029,91,2015-11-02 19:00:00-05:00,17.450000,17.283333,17.483333,2.054841e+03,2.035880e+03,2.021660e+03,2.028770e+03

In [7]:
test = data2[data2["target"] == 0]
test

,obs_id,site_id,timestamp,temperature,temperature_-1,temperature_-2,load,load_-1,load_-2,target
5,51,78,2017-05-15 03:00:00-04:00,15.500000,13.000000,12.900000,1.006653e+06,748475.882297,5.781718e+05,0.0
6,55,78,2016-12-15 10:00:00-05:00,2.000000,2.000000,1.833333,8.733329e+05,941881.203449,1.029805e+06,0.0
7,60,78,2017-02-03 11:00:00-05:00,8.133333,9.000000,9.000000,5.052074e+05,590755.741385,5.791804e+05,0.0
8,70,78,2017-03-17 14:00:00-04:00,18.766667,19.700000,20.550000,6.957117e+05,848383.949112,9.185337e+05,0.0
9,77,78,2017-01-06 12:00:00-05:00,0.000000,1.733333,2.500000,2.062510e+05,172491.350176,2.211416e+05,0.0
...,...,...,...,...,...,...,...,...,...,...
5371,5326,91,2015-07-28 19:00:00-04:00,23.466667,24.220000,25.420000,1.924487e+03,1893.676550,1.936338e+03,0.0
5372,5353,91,2016-08-13 21:00:00-04:00,17.600000,18.783333,20.000000,1.476546e+03,1491.951675,1.520392e+03,0.0
5373,5354,91,2016-05-24 15:00:00-04:00,19.833333,21.333333,21.533333,1.540538e+03,1750.288025,2.842885e+03,0.0
5374,5360,91,2015-06-20 01:00:00-04:00,19.450000,19.516667,19.866667,1.944633e+03,1947.002861,1.976629e+03,0.0
5375,5364,91,2016-09-24 16:00:00-04:00,20.716667,22.420000,23.660000,1.546463e+03,1558.313306,1.618750e+03,0.0

## Data3: Submission data

In [8]:
submission = pd.read_csv("cold-start-consumption-forecasting-submission-data.csv", sep=";", parse_dates=['timestamp'])
submission

      obs_id  site_id                  timestamp leaderboard_target  target
0       3013       86  2017-05-03 20:00:00-04:00            private     0.0
1       3018       86  2017-03-13 02:00:00-04:00            private     0.0
2       3062       87  2015-03-20 16:00:00-04:00             public     0.0
3       3081       87  2015-07-30 02:00:00-04:00             public     0.0
4       3090       87  2016-09-30 21:00:00-04:00             public     0.0
...      ...      ...                        ...                ...     ...
4699    4666       91  2015-09-05 08:00:00-04:00            private     0.0
4700    4670       91  2015-07-16 22:00:00-04:00            private     0.0
4701    4679       91  2016-03-15 19:00:00-04:00            private     0.0
4702    4686       91  2015-09-18 11:00:00-04:00            private     0.0
4703    4696       91  2017-06-26 02:00:00-04:00            private     0.0

[4704 rows x 5 columns]

In [9]:
submission.describe()

            obs_id      site_id  target
count  4704.000000  4704.000000  4704.0
mean   2351.500000    84.500000     0.0
std    1358.072163     4.031557     0.0
min       0.000000    78.000000     0.0
25%    1175.750000    81.000000     0.0
50%    2351.500000    84.500000     0.0
75%    3527.250000    88.000000     0.0
max    4703.000000    91.000000     0.0

## Data4: Meta data

In [10]:
metadata = pd.read_csv("cold-start-consumption-forecasting-meta-data.csv", sep=";")
metadata

,obs_id,site_id,surface,base_temperature,monday_is_day_off,tuesday_is_day_off,wednesday_is_day_off,thursday_is_day_off,friday_is_day_off,saturday_is_day_off,sunday_is_day_off
0,1,88,17.321667,18.0,False,False,False,False,False,True,True
1,39,65,700.616167,18.0,False,False,False,False,False,True,True
2,77,46,487.124678,18.0,False,False,False,False,False,True,True
3,0,28,1334.976110,18.0,False,False,False,False,False,True,True
4,12,2,10060.060936,18.0,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...
86,38,14,16355.878746,18.0,False,False,False,False,False,True,True
87,55,53,5996.254722,18.0,False,False,False,False,False,True,True
88,70,85,1887.420261,18.0,False,False,False,False,False,True,True
89,71,50,13357.690454,18.0,False,False,False,False,False,True,True
90,79,18,13999.177368,18.0,False,False,False,False,False,True,True

In [11]:
metadata.describe()

         obs_id   site_id       surface  base_temperature
count  91.00000  91.00000     91.000000         91.000000
mean   45.00000  46.00000   8201.376102         18.021978
std    26.41338  26.41338  11379.584643          0.209657
min     0.00000   1.00000     14.884534         18.000000
25%    22.50000  23.50000   1118.799075         18.000000
50%    45.00000  46.00000   3580.148991         18.000000
75%    67.50000  68.50000  12281.567083         18.000000
max    90.00000  91.00000  71615.852476         20.000000

## Data5: Holidays data

In [12]:
holidays = pd.read_csv("cold-start-consumption-forecasting-holidays-data.csv", sep=";")
holidays

      obs_id  site_id                              holiday        date
0         20       20               Confederate Heroes Day  2017-01-19
1         32       20    Texas Independence Day (Observed)  2014-03-03
2         47       20                             New year  2015-01-01
3        112       34                         Memorial Day  2015-05-25
4        122       34  Birthday of Martin Luther King, Jr.  2017-01-16
...      ...      ...                                  ...         ...
3282    3211       53                     National Holiday  2017-10-26
3283    3216       53                       All Saints Day  2016-11-01
3284    3232       56                             New year  2016-01-01
3285    3239       56         Assumption of Mary to Heaven  2015-08-15
3286    3282       36                        Christmas Day  2016-12-25

[3287 rows x 4 columns]

In [13]:
holidays.describe()

            obs_id      site_id
count  3287.000000  3287.000000
mean   1643.000000    45.721935
std     949.019494    26.162549
min       0.000000     1.000000
25%     821.500000    22.000000
50%    1643.000000    46.000000
75%    2464.500000    68.000000
max    3286.000000    91.000000